replicaCount: 1
name: frigate
targetPort: 5000
frigate:
  envFromSecrets:
    - name: frigate-secrets
      secretName: frigate_camera_password_fancy
    - name: frigate-secrets
      secretName: frigate_camera_password_lower
    - name: frigate-secrets
      secretName: frigate_mqtt_password
  tmpfs:
    enabled: true
    sizeLimit: 1Gi
  coral:
    enabled: "true"
  shmSize: 1Gi
  service:
    port: 5000
    type: ClusterIP
  ingress:
    enabled: "true"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/host: frigate.frost.haus
    hosts:
      - host: frigate.frost.haus
        paths:
          - path: '/'
            portName: http
    tls:
      - hosts:
        - frigate.frost.haus
        secretName: frigate-cert
  persistence:
    config: 
      enabled: "true"
      size: 2Gi
      accessMode: ReadWriteOnce
      storageClass: "synology-csi-iscsi-delete"
    media:
      enabled: "true"
      size: 20Gi
      accessMode: ReadWriteOnce
      storageClass: "synology-csi-iscsi-delete"
  resources:
    limits:
      memory: 1Gi
      nvidia.com/gpu: "1"
    requests:
      cpu: "1"
      memory: 1Gi
      nvidia.com/gpu: "1"
  gpu:
    nvidia: 
      enabled: "false"
      runtimeClassName: nvidia	
  config: |
    mqtt:
      host: homeassistant.brainboy.local.lan
      port: 1883
      topic_prefix: frigate
      client_id: frigate
      user: SMASH
      password: {FRIGATE_MQTT_PASSWORD}
      stats_interval: 60
    birdseye:
      enabled: true
      width: 1280
      height: 720
      quality: 8
      mode: motion
    go2rtc:
      streams:
        bnb_barn:
          # - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.198:554/h264Preview_01_main
          - ffmpeg:http://192.168.100.198/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Gr33n3ggs!#video=copy#audio=copy#audio=opus
        bnb_barn_sub:
          # - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.198:554/h264Preview_01_sub
          - ffmpeg:http://192.168.100.198/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Gr33n3ggs!
        bnb_doors:
          # - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.151:554/h264Preview_01_main
          - ffmpeg:http://192.168.100.151/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Gr33n3ggs!#video=copy#audio=copy#audio=opus
        bnb_doors_sub:
          # - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.151:554/h264Preview_01_sub
          - ffmpeg:http://192.168.100.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Gr33n3ggs!
        bnb_front_door:
          - rtsp://administrator:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.126:554/stream1
        bnb_front_door_sub:
          - rtsp://administrator:{FRIGATE_CAMERA_PASSWORD_FANCY}@192.168.100.126:554/stream2
        bnb_living_room:
          - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_LOWER}@192.168.100.162:554//h264Preview_01_main
        bnb_living_room_sub:
          - rtsp://admin:{FRIGATE_CAMERA_PASSWORD_LOWER}@192.168.100.162:554//h264Preview_01_sub
    cameras:
      BnB_barn:
        snapshots:
          enabled: true
          timestamp: true
          bounding_box: true
          retain:
            default: 28
            # mode: active_objects
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/bnb_barn
              input_args: preset-rtsp-restream
              roles:
                - record
                - audio
            - path: rtsp://127.0.0.1:8554/bnb_barn_sub
              input_args: preset-rtsp-restream
              roles:
                - detect
          output_args:
            record: preset-record-generic-audio-aac
      BnB_doors:
        snapshots:
          enabled: true
          timestamp: true
          bounding_box: true
          retain:
            default: 28
            # mode: active_objects
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/bnb_doors
              input_args: preset-rtsp-restream
              roles:
                - record
                - audio
            - path: rtsp://127.0.0.1:8554/bnb_doors_sub
              input_args: preset-rtsp-restream
              roles:
                - detect
          output_args:
            record: preset-record-generic-audio-aac
        zones:
          Porch-from-side:
            coordinates: 0.478,0.177,0.997,0.165,0.994,0.984,0.481,0.984
            loitering_time: 0
      BnB_front_door:
        audio:
          enabled: false
        snapshots:
          enabled: true
          timestamp: true
          bounding_box: true
          retain:
            default: 28
            # mode: active_objects
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/bnb_front_door
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/bnb_front_door_sub
              input_args: preset-rtsp-restream
              roles:
                - detect
        motion:
          mask:
            - 0.263,0.521,0.315,0.516,0.322,0.604,0.252,0.6
            - 0.53,-0.001,0.529,0.106,0.633,0.111,0.642,0
        objects:
          filters:
            car:
              mask:
                - 0.235,0.525,0.226,0.457,0.001,0.462,0.005,0.613
                - 0.419,0.469,0.497,0.467,0.501,0.519,0.416,0.513
                - 0.232,0.452,0.297,0.461,0.3,0.497,0.238,0.493
        zones:
          Porch:
            coordinates: 0,0,1,0,0.999,0.984,0.001,0.989
            loitering_time: 0
            inertia: 3
      BnB_living_room:
        objects:
          track:
            - person
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/bnb_living_room
              input_args: preset-rtsp-restream
              roles:
                - record
                - audio
            - path: rtsp://127.0.0.1:8554/bnb_living_room_sub
              input_args: preset-rtsp-restream
              roles:
                - detect
    # detectors:
    #   coral:
    #     type: edgetpu
    #     device: usb
    record:
      enabled: true
      alerts:
        retain:
          days: 14
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 14
        pre_capture: 5
        post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 28
        mode: active_objects
    objects:
      track:
        - bird
        - person
        - car
        - cat
        - dog
        - face
        - license_plate
        - car
        - amazon
        - fedex
        - ups
        - package
        - deer
        - motorcycle
        - bicycle
        - boat
        - usps
        - dhl
        - horse
        - raccoon
        - fox
        - bear
        - cow
        - squirrel
        - goat
        - rabbit
        - waste_bin
        - bbq_grill
        - robot_lawnmower
        - umbrella
    model:
      path: plus://39ea8f8fddecc75b5a46dc74342d24c7
      path: /edgetpu_model.tflite
      labelmap_path: /labelmap.txt
      width: 320
      height: 320
      input_pixel_format: rgb
      input_tensor: nhwc
      labelmap:
        2: vehicle
      attributes_map:
        person:
          - amazon
          - face
        car:
          - amazon
          - fedex
          - license_plate
          - ups
    ffmpeg:
      # hwaccel_args: preset-vaapi
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt 
        -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 
          -strftime 1 -c copy -an
    live:
      height: 720
      quality: 8
    telemetry:
      network_interfaces: []
      stats:
        amd_gpu_stats: false
        intel_gpu_stats: true
        network_bandwidth: true
      version_check: true
    semantic_search:
      enabled: true
      # model_size: large
      # model_size: small
      reindex: true
      model_size: large
    genai:
      enabled: true
      provider: ollama
      base_url: http://ollama.frost.haus
      # model: llama2:latest
      model: llava:7b
      prompt: Analyze the {label} in these images from the {camera} security camera.
        Focus on the actions, behavior, and potential intent of the {label}, rather 
        than just describing its appearance.
      object_prompts:
        person: Examine the main person in these images. What are they doing and 
          what might their actions suggest about their intent (e.g., approaching a 
          door, leaving an area, standing still)? Do not describe the surroundings 
          or static details.
        car: Observe the primary vehicle in these images. Focus on its movement, 
          direction, or purpose (e.g., parking, approaching, circling). If it's a 
          delivery vehicle, mention the company.
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 500
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
      filters:
        speech:
          threshold: 0.8
    version: 0.15-1