apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production-arr
  namespace: argocd
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}