replicaCount: 1
name: speedtest-tracker
targetPort: 80
puid: 1026
pgid: 100

image:
  repository: lscr.io/linuxserver/speedtest-tracker
  tag: "1.15.0"
  pullPolicy: IfNotPresent

speedtestSchedule: "6,36 * * * *"
adminName: Admin
adminEmail: bfrost@brainboy.com
