apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: overseerr-pvc
  name: overseerr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gb
  storageClassName: synology-csi-iscsi-delete
