apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: overseerr-claim0
  name: overseerr-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: synology-csi-iscsi-delete
