apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/bfrost/tempo.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: overseerr
  name: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/bfrost/tempo.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: overseerr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/overseerr:latest
          name: overseerr
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: overseerr-claim0
      restartPolicy: Always
      volumes:
        - name: overseerr-claim0
          persistentVolumeClaim:
            claimName: overseerr-claim0
