apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: overseerr
  name: overseerr
spec:
  selector:
    io.kompose.service: overseerr
  type: ClusterIP
  ports:	
  - port: 443
    name: https
    targetPort: 5055
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: overseerr.k8s.frost.haus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - overseerr.k8s.frost.haus
    secretName: overseerr-cert
  rules:
  - host: overseerr.k8s.frost.haus
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: overseerr
            port:
              number: 80
