replicaCount: 1
name: sabnzbd
targetPort: 8080
puid: 1026
pgid: 100
timezone: America/Chicago

image:
  repository: linuxserver/sabnzbd
  # renovate: datasource=docker depName=linuxserver/sabnzbd
  tag: "5.1.1"
  pullPolicy: IfNotPresent
