apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: {{ .Values.name }}-ui.frost.haus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.name }}-ui.frost.haus
    secretName: {{ .Values.name }}-cert
  rules:
  - host: {{ .Values.name }}-ui.frost.haus
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: kagent
            port:
              name: ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: {{ .Values.name }}-app.frost.haus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.name }}-app.frost.haus
    secretName: {{ .Values.name }}-cert
  rules:
  - host: {{ .Values.name }}-app.frost.haus
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: kagent
            port:
              name: app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-controller
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: {{ .Values.name }}-controller.frost.haus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.name }}-controller.frost.haus
    secretName: {{ .Values.name }}-cert
  rules:
  - host: {{ .Values.name }}-controller.frost.haus
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: kagent
            port:
              name: controller