apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-prod
  source:
    path: argocd/charts
    repoURL: https://github.com/bdfrost/argocd
    targetRevision: HEAD