---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kometa-secret
  namespace: kometa
spec:
  encryptedData:
    tmdb_token: AgBl0jOS2ZqgvUD3mRT1JLoXKIcTvFmzPcS8dnxgR0jn5C075uVF4cwq8qjA5tdYyaKR2d7A4uVfEjfUEnLAR1A7Ol7asrucmwit64iFH09lJEkEBzpzJC1X3T+OcD69kIQTOJxTD7VxV8VC1I3mPJUPgXiIaA66K+tIpd3wt4OVoXJFRsgozK+GmGYabGEAlTvyxe1AqIw6FamqNAAia4K+isA7q2BQZk92v0+JFnVMQNVlDgWXwtDCuXUgfmMku7hHTOfrsOvoEoTPo6ewLQ4bQhCcqy6MKmfMuWfQ5EXviXu1Gr/JuvyZ65fXwV4bHLVkumf/RdgdfNRHgv2IXgGvSfy+Pdm6NxyQZ4TKRFZptp6e4nW3BYv5AZjBLpWgvtOMrZb6+Xa/gM4ZbUJNKUyXo2b1Dg4NRmLdpPt2UpED0toQbcFZXnxU/3UwJhtfOOMdLXn5dyfU11o9domxcyY8Syr6LqslUMDIU8X9GB/6b3fb7s0G3t/xCDrgSDyenA2otyLTZk9kl6NhvKK3SMGJHuY19nMiBTOTYEIvy+aPdCZP9u99IwGk8avPHnaYE4m23rFwVXK9BSTXF9AZ2Vg6/Jl1py7rmllP0rdGd0IauI66svILIqf/Y3k+3SViSg3QdZNLLqYVGcy0w7uGsUlOw86a39D8z82+/SgHmbNmsaD0nb5V7RB+pEs13fq3zs+Bn+D1og6V6cPTKPqMY+z6zTCFeMqy918=
  template:
    metadata:
      creationTimestamp: null
      name: kometa-secret
      namespace: kometa
