replicaCount: 1
name: homepage
pgid: 1000
puid: 1000

homepage:
  env:
    TZ: "America/Chicago"
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
  rbac:
    enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    create: true
    automount: true
    name: ""