apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.name }}/{{ .Values.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SABNZBD_UID
          value: "1000"
        - name: SABNZBD_GID
          value: "1000"
        volumeMounts:
        - name: {{ .Values.name }}
          mountPath: /datadir
        - name: sabnzbd-downloads
          mountPath: /download
        resources:
          limits:
            memory: 50Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 10m
      volumes:
      - name: {{ .Values.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.name }}
      - name: sabnzbd-downloads
        hostPath:
          path: /mnt/fileserv/Library