apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: linuxserver/sabnzbd
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.targetPort }}
        env:
        - name: HOST_WHITELIST_ENTRIES
          value: sabnzbd.frost.haus
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: PGID
          value: "{{ .Values.pgid }}"
        - name: PUID
          value: "{{ .Values.puid }}"
        - name: HAS_IPV6
          value: "false"
        volumeMounts:
        - name: {{ .Values.name }}-config
          mountPath: /config
        - name: arr-media
          mountPath: /data
        - name: temp-local-storage
          mountPath: /download-temp
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 600Gi
          requests:
            cpu: "2"
            memory: 2Gi
            ephemeral-storage: 600Gi
      volumes:
        - name: {{ .Values.name }}-config
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-config-pvc
        - name: arr-media
          nfs:
            server: 192.168.100.250
            path: /volume1/media
        - name: temp-local-storage
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 2Gi
