apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.name }}
spec:
    capacity:
        storage: 500Mi
    volumeMode: Filesystem
    accessModes:
    - ReadWriteOnce
    type: csi
    