apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.spec.name }}
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    nfs:
        path: /mnt/fileserv/kubernetes/{{ .Values.spec.name }}
        server: 10.0.1.14