apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.name }}
  labels:
    app: {{ .Values.spec.name }}
    kubernetes.io/name: {{ .Values.spec.name }}
spec:
  selector:
    app: {{ .Values.spec.name }}
  ports:
  - name: {{ .Values.spec.name }}
    port: 80
    targetPort: 8080