apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/bfrost/tempo.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: recommendarr
  name: recommendarr
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: recommendarr
