replicaCount: 1
name: open-webui
open-webui:
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: "2"
      memory: 2Gi
  ollama:
    enabled: false
  ollamaUrls:
    - "http://ollama.frost.haus"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClass: "synology-csi-iscsi-delete"
  service:
    labels:
      app: open-webui
      kubernetes.io/name: open-webui