apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn
spec:
  backupTargetURL: nfs://192.168.100.250:/mnt/media?nfsOptions=soft,timeo=330,retrans=3
  credentialSecret: ""
---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: gcp-backups
  namespace: longhorn
spec:
  backupTargetURL: s3://brainboy-longhorn@us-central1/
  credentialSecret: longhorn-gcp-backups