apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: {{ .Values.name }}.frost.haus
spec:
  tls:
  - hosts:
    - {{ .Values.name }}.frost.haus
    secretName: {{ .Values.name }}-cert
  rules:
  - host: {{ .Values.name }}.frost.haus
    # ingressClassName: nginx
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: longhorn
            port:
              name: http
