
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-snapshots
  namespace: longhorn
spec:
  concurrency: 1
  cron: '*/4 0 * * *'
  groups:
  - default
  - arr
  labels: {}
  name: hourly-snapshots
  parameters: {}
  retain: 60
  task: snapshot
---    
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backups
  namespace: longhorn
spec:
  concurrency: 1
  cron: 0 2 * * ?
  groups:
  - default
  - arr
  labels: {}
  name: daily-backups
  parameters:
    full-backup-interval: "7"
  retain: 28
  task: backup
