
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-snapshots
  namespace: longhorn
spec:
  concurrency: 1
  cron: */4 * * * *
  groups:
  - default
  - arr
  labels: {}
  name: hourly-snapshots
  parameters: {}
  retain: 120
  task: snapshot
---    
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: sunday-backups
  namespace: longhorn
spec:
  concurrency: 1
  cron: 0 2 * * ?
  groups:
  - default
  - arr
  labels: {}
  name: sunday-backups
  parameters:
    full-backup-interval: "7"
  retain: 28
  task: backup
