apiVersion: v1
kind: ConfigMap
metadata:
  name: autokuma-static-monitors
data:
  services.json: |-
    [
      {
        "name": "Homepage",
        "type": "http",
        "url": "https://homepage.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Argo CD",
        "type": "http",
        "url": "https://argocd.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-399"]
      },
      {
        "name": "Poterie",
        "type": "http",
        "url": "https://poterie.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Plex",
        "type": "http",
        "url": "https://peppers.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299", "401"]
      },
      {
        "name": "Tautulli",
        "type": "http",
        "url": "https://tautulli.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Seerr",
        "type": "http",
        "url": "https://seerr.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Sonarr",
        "type": "http",
        "url": "https://sonarr.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Radarr",
        "type": "http",
        "url": "https://radarr.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Prowlarr",
        "type": "http",
        "url": "https://prowlarr.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Bazarr",
        "type": "http",
        "url": "https://bazarr.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "SABnzbd",
        "type": "http",
        "url": "https://sabnzbd.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Grafana",
        "type": "http",
        "url": "https://grafana.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Prometheus",
        "type": "http",
        "url": "https://prometheus.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Alertmanager",
        "type": "http",
        "url": "https://alertmanager.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Portainer",
        "type": "http",
        "url": "https://portainer.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Netdata",
        "type": "http",
        "url": "https://netdata.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "BirdNET-Go",
        "type": "http",
        "url": "https://birdnet-go.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "SimpleFIN",
        "type": "http",
        "url": "https://simplefin.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299", "401"]
      },
      {
        "name": "DNS1",
        "type": "http",
        "url": "https://dns1.frost.haus:53443",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-399"]
      },
      {
        "name": "DNS2",
        "type": "http",
        "url": "https://dns2.frost.haus:53443",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-399"]
      },
      {
        "name": "Home Assistant",
        "type": "http",
        "url": "http://homeassistant.frost.haus:8123/",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-399"]
      },
      {
        "name": "Dozzle",
        "type": "http",
        "url": "https://dozzle.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-299"]
      },
      {
        "name": "Uptime Kuma",
        "type": "http",
        "url": "https://uptime-kuma.frost.haus",
        "interval": 60,
        "max_retries": 2,
        "accepted_statuscodes": ["200-399"]
      }
    ]
