---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-management
  namespace: uptime-kuma
spec:
  encryptedData:
    password: AgA2TDcjVo7vWkYnDM026tlW3o7Jj/c8IJTyIOeYiZJ/oSlnJZIsiaNFzqLIkveQ5jiNlBMXymlJurvtTpd/cx+9FQ+Jlg+jt3DOZhWrWJC6w7WhNO1r/7DcUxgr8eJ3H7EYa2zC9MQC9XODMMGDbtv0+GYlxIrMfKDW9dE6l6chOurxk3UV1up8tp2ThOyKsS+pQ+ltsFFkPE2wCOHEDH4ya/HkqZ+Sq03Pl5qSgIKNnAagc1hL7sIIEbChY8FoTw2pb0A9BDGDZqTQbdJKWj1QUwwe6GIQI254/9robyO5Zpm7HZihMIox/0o+HwJPOUXuvD5PkD6HK8vhip0dCw08lt4BPDIMtkhHtfd3c4oNJDp5HJEFuzFxZC+mZUk6OyHXfSnROXLqjkr/7ObkMO/XsHtPPyxXPsXDtemBo8tDkyEybKQ9KGa3lEXggPFTB5uyoGkTtGa8adB6G/v/TwcYbQ3FfADhKIs0osLYP4QEABSiHA52UhKxybkvXx2jAR+SvqswMn1x5+ssx0MaL6KhyiyXIZZ+v5mRSUxM2LqoHa0dmQOZsFMylgoG0qGaPD0Pt4KfXx/4snky+mw/F9VjLj+lxxxNk5jTmFTO0pResEReE2+v+OyiRFTiZ19UCqBcNlqYlMcfzLme1+AC+9AMVdl7WXzXWYH8flTXMJ3B/SkL9wg6Lz++hhx2/HqRqSBMc0HzDAtb8CwQBBp+LXRJ5+Lz
    username: AgA2nqF9Ny1XVZVl07fYNiDvJdv14mYNKKSweppE0zaaJuAnKw8OWO9zv9OM8be0gLJx5DskgizJm8xshcdg7gKep8LfdN4nuBtN7YYJ1GW0jDKkymo2wka5534SWhEGFaLZ/PLlkjKfU5f1NPIwebAjB5eVruN5SMbLUrY2d69c+Cp13doghaJ8V3rshc0L0YGNF9O4xHeLMxGb6Vqp4vTcO5UFptyafueIBIvZYYA6TDgdc47C6cZQ9pmlip2TMViLya4fLAfcb+ID5DCB6aOtoBrHCsK3bv+qPd6lS3z3oxjwM3IrD4UtrbsQarDvIT/Erz+0tTHk01Vg2TmIyqLwG7YZ4NHdGwTj56FUozfCfANWhr3w9PTe9dZGK45msdXSijhibKk/i9Fd9I8knex6ItU/jZYWl61YTi+WNk/0hjdth1LStGwX/JV8zL4jitfH4d9YE2XFH24ePdEWGyN9vSBnBzRIEpWxjLaLRSazL7pHZy4e/zkSigKBKb7duzEYBBv3UVIWQTpTDA47FaeEvHq9INmQjKwuKfjIv2pffYQxsmULVNgL0pPFIpbc4TxtffuRvXnY3QzD5NlGuViOq1gfZ3OkFK4uHD128HiU0FCiIvZzcKTx9QYnSHrxhukIroqBz2MXBfwosiN2D1LLNVgRmMDEasoe44+c90aSEvslPrsnMwtTlVdXnbh5aVeTbZeA7PI=
  template:
    metadata:
      name: uptime-kuma-management
      namespace: uptime-kuma
