{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: immich-database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
{{- end }}
