---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres
  namespace: immich
spec:
  encryptedData:
    password: AgCdCSb0a3VU317bTlNKXHTjg3p4FQo9lSa+//hlF6PsyWrA3v1PClRGk8yhOONEzmUvOCn4L8zKX2TScC2ZPGc2xV6cna+8HEsF9Ird4331ghZmgkBKx2JH1A/A3HIcl6F3sAanJx9OXdDppHhltj98oSPOrNr0xnCsKlTKM1woHIk2wOr9so0WauWCjHKUfdpTuz2c5zo5dByeoWH1mcw/UEE+tEuH9HlmUjWyBBGBeW+ww6QqsEzvEPZbtKgOE83rakWcmDfqUHM/VADxxuFzSIc+8qaA+OFomdkBbyNL8aGmuQxX6SKO58yZXZmiDjdyUVIRzlYE+9VkVrcDnzl2kX93ADLiYGH5zDae/3P+iryKiMULwiWCNWkf1KxIer/0RILXCdOLJyOL+1xitHWZ+HkCVzLstvcB+AdMCZJifE8AhR9F9mprgNbe3KJIwlP0/oDKlTz9CQ3Kqsijke9gpPvnD3/qid+UHK5lOXy19Ss2ePumDCkEhBXSjS5+wBlrltXcqxapGh2VeGFVzNoy3TrD9036iB9xzCwye862wBri36YOPzCzpYl7XzA8XrbDQnK3icurcklHuW6yPq8JUAY2J4H5EiGMshWf7ELOSq5s9H9UPR2YJrRBcs/80awPcOOYkWxecaBwOCSUx0qDmNICIZCppwC5myN5DmtjyVw+/GAmNd1xrVv2qtfXzVK5XFDLnYL/PV+vQJfEyQIMMz+234y2mWA1huuA0Mn37RISUej+Hlzx
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres
      namespace: immich
