---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gphotos
  namespace: gphotos
spec:
  encryptedData:
    client-secret.yaml: AgAJrvtcAY9Z/xDvTphxnO5/VXb26EA0fd0pG5hC/GF4/zXGzEUlLSuOxmzZtuDyC4NZiWd52L9uOWmurJWIILi/FL/oxihrpnshAzxSoOsviQTxJwT9YaTxkpdJMZq7VLs7qBhAIRCRs7QtIWrPrzdbKZTKnYk92bpOgrTX+Inoa0FBHs+udevlPZ4JcyrEd2xq49bknHboF82GwhMtopOhh3VMTTJ++b6mVa4r1PBXBDr3R312CU/AGcLiQGTFeckCWKGy6FxeqqeA0OP9enQxlaPDJNiMDCyRXT/yxXR39ZqNKid9y3wx4GBgiFJJ9Psl7Ve+giz51WiuCzhPoI6MQkp7NtF2X5I+KMk91SpF010vJ8SU+Ek3SszXcDeOqajTSjLby0rp+7D53FEcX5rSLXTuGZRQHuf9QP+i1J+/QHuoO9TwjDfhrj1exvh/p3oQ9rIltMhjgMqlDb//J6pahR+rFQQqcSCSSPYoVaa7l+Gqo6ZfyaR7d9BUmwATXhnx0KDdVvrPE39D+b7iXCs9aSHTE30128XH15k9q7++0A9NehlO+rKl5ZdZsr+Up+GXdkPlMQEDWbyP8oFyhqTAznM5OiduHnWjFemm0iDM+k1KtPq9B1EB38DZzpZt5mpbnncEtRmMvP908RiJYRxjYlvP2BLjz3uSL0cjWMw5lkklTBMCRsQDY0IeBBiVtVSQjVoXmjnbjuMwMNHHc8LAJEFBzwhpthvKYYpD2MdyimbXCa767jULQb3tVF3RJ5/rvc1RAGnq2tHENniDfE8tiHNSTtY1E3f0PKv512bF8etot8R4nr8lV9MbQP1yMV8bYVDTykRXygXaTI5J3wPI3cNjqss32uB0CjwstDS/v3XrLGnuXeXIsp5ybeFIobLneBXyc9/EHZbXMPxDRfj+JfiU/6cyvQvVnnQDILweNvOpbaWBFn47m1/HTmp3t2wx/9zDDQmXpPb/67/MU9J28Ke9tubPFvThZGPsQ3mrEmkzTtVgV8YKWd0C6bhqRGWxIEnlx1n/tlMI76TmUR4HqGXAVTTP2TJPW//vCW3EqgOGoAJe4Bsj5+A3zC2EtxpkhKBhWxQ326YRKhCurQ57k1r1fwNi38vyyuUiIxVPaSrPBad5n96iH3HldVa+Qhul4cD/r4G95rUS74zg685es84LEuzNrRXBhlrUY95K+Et9aLVNm3IBdQ0nLEZw0sQeXBPJSIAA+Nyy5Pcn4Uw6k5y/UPb0gdXU
  template:
    metadata:
      creationTimestamp: null
      name: gphotos
      namespace: gphotos
