replicaCount: 1
name: portainer
targetPort: 9000
puid: 1026
pgid: 100
portainer:
  localMgmt: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/host: portainer.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - hosts:
        - portainer.frost.haus
        paths: /
    tls:
      - hosts:
        - portainer.frost.haus
  persistence:
    enabled: true
    size: "10G"
    storageClass: synology-csi-iscsi-delete
  # tls:
  # - hosts:
  #   - {{ .Values.name }}.frost.haus
  #   secretName: {{ .Values.name }}-cert
  # rules:
  # - host: {{ .Values.name }}.frost.haus
  #   http:
  #     paths:
  #     - pathType: ImplementationSpecific
  #       path: "/"
  #       backend:
  #         service:
  #           name: {{ .Values.name }}
  #           port:
  #             name: http