replicaCount: 1
name: portainer
targetPort: 9000
puid: 1026
pgid: 100
portainer:
  localMgmt: true
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: "10G"
    storageClass: synology-csi-iscsi-delete
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/host: portainer.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: portainer.frost.haus
        paths:
          - path: /
    tls:
      - hosts:
        - portainer.frost.haus
        secretName: portainer-cert