replicaCount: 1
name: portainer
targetPort: 9000
puid: 1026
pgid: 100
portainer:
  localMgmt: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/host: portainer.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
  persistence:
    enabled: true
    size: "10G"
    storageClass: synology-csi-iscsi-delete
    hosts:
      - host: portainer.frost.haus
        http:
          paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: portainer
                port:
                  name: http
    tls:
    - hosts:
      - portainer.frost.haus
      secretName: portainer-cert
  # rules:
  # - host: {{ .Values.name }}.frost.haus
  #   http:
  #     paths:
  #     - pathType: ImplementationSpecific
  #       path: "/"
  #       backend:
  #         service:
  #           name: {{ .Values.name }}
  #           port:
  #             name: http