replicaCount: 1
name: tautulli
targetPort: 8989
puid: 1026
pgid: 100
ingress:

tautulli:
  env:
    TZ: "America/Chicago"
  image:
    repository: tautulli/tautulli
    tag: v2.16.0
    pullPolicy: IfNotPresent
  service:
    main:
      ports:
        http:
          port: 8181
  ingress:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      storageClassName: synology-csi-iscsi-delete
      existingClaim: "tautulli-config-pvc"