replicaCount: 1
name: tautulli
targetPort: 8989
puid: 1026
pgid: 100
ingress:

tautulli:
  env:
    TZ: "America/Chicago"
  image:
    repository: ghcr.io/k8s-at-home/tautulli
    tag: v2.10.5
    pullPolicy: IfNotPresent
  service:
    main:
      ports:
        http:
          port: 8181
  ingress:
    main:
      enabled: false
  persistence:
    config:
      enabled: false