---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-exporter
  namespace: sabnzbd-exporter
  labels:
    app.kubernetes.io/name: sabnzbd-exporter
    app.kubernetes.io/instance: sabnzbd-exporter
spec:
  selector:
    app.kubernetes.io/name: sabnzbd-exporter
    app.kubernetes.io/instance: sabnzbd-exporter
  ports:
    - name: monitoring
      port: 9707
      protocol: TCP
      targetPort: 9707
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sabnzbd-exporter
  namespace: sabnzbd-exporter
  labels:
    app.kubernetes.io/name: sabnzbd-exporter
    app.kubernetes.io/instance: sabnzbd-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd-exporter
      app.kubernetes.io/instance: sabnzbd-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sabnzbd-exporter
  namespace: sabnzbd-exporter
  labels:
    app.kubernetes.io/name: sabnzbd-exporter
    app.kubernetes.io/instance: sabnzbd-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd-exporter
      app.kubernetes.io/instance: sabnzbd-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd-exporter
        app.kubernetes.io/instance: sabnzbd-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: sabnzbd-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - sabnzbd
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://sabnzbd.sabnzbd.svc.cluster.local"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "sabnzbd-exporter",
    "namespace": "sabnzbd-exporter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "sabnzbd-exporter",
        "namespace": "sabnzbd-exporter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgBy3WJOwFrr/wCQD8Sle4OuXVer8mP30+hdaeaF2Ck1ubHSyNWgpmuVmN/wwi0/W8PRsQPswcPrTonui6s7wguFRqweaPlkpCPBCVJusTQR3rZahxFU4Ar4dQTHVtXQOHnq0z18ghtr/GSTeBc8toBbBVA2y51UZpsruogeE4D5R33TbLgNuXYuuD7Kpf50lg4aZ8Zq2gSkA4JKK3epcWhSZPKxLZeOiMh/FoW1N0BaXUGueX1d0ruX+tLcDFN6pTMGmB99/R7KeUDhTMiDNC2OYbqcR1TgvdPCjxID7mKZxfenfkDraSjWoiTCYeO8plr/dMZS28aNc7bW6TPii+FMK6H7Bhd3WbaBXI6nKGg9dDNSR+gn7SSz82E3LKoEroOh6eIryMBFFko/h21j7sdSmcvet32gi85tS24gEMheJ5O/Ka7AepwyucPL45jWzV5ioX9V5puT9mj7JmCVIEBhOAR0HjZzUuW6nH8z00s8qMs95HHUTiyP9pjOSTMmoVCPLhbgZUv/KD/pLBXEekd5YadrnFplaOZ/wUAw7hh3SFbuRzGY8/X5N+YeP8jqMBx1z25mJ3+arPlEcQqkwvMD2VwCSbg2kiN25dyJZFygJeA8qh1T9fd14Drlyfq6zt+r8M3VLV8OKuqtTW862SycAd9/AzPEm+pBQaqt67COlLtbuWTngyrY6TuOCprtfCLZ+BSzv8IhS16Q1CxTSZTt9t3h3AUkbrJY/g0+66gmLA=="
    }
  }
}