---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-exporter
  namespace: sonarr-exporter
  labels:
    app.kubernetes.io/name: sonarr-exporter
    app.kubernetes.io/instance: sonarr-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: sonarr-exporter
    app.kubernetes.io/instance: sonarr-exporter
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr-exporter
  namespace: sonarr-exporter
  labels:
    app.kubernetes.io/name: sonarr-exporter
    app.kubernetes.io/instance: sonarr-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr-exporter
      app.kubernetes.io/instance: sonarr-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr-exporter
  namespace: sonarr-exporter
  labels:
    app.kubernetes.io/name: sonarr-exporter
    app.kubernetes.io/instance: sonarr-exporter
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.sonarr-exporter: semver:~v0.1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr-exporter
      app.kubernetes.io/instance: sonarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr-exporter
        app.kubernetes.io/instance: sonarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: sonarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - sonarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://sonarr.default.svc.cluster.local:7878"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sonarr-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "sonarr-exporter",
    "namespace": "sonarr-exporter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "sonarr-exporter",
        "namespace": "sonarr-exporter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgAT+kPjaEsb3vMongPeQjoOd6yjXcp4onZP5JgTiGZK+WHJnpzAdI1GHOV7hoMF/dXCHNkGjF/rMLofATtznWtZu+6tb8Jm1aOPbyEu1TfoT66jDX/AuirKfr/MAGYd+OL0fvXfUztgiFG3+htmKF33DN0urzkhZwlUPeMD5Wx4NCaNKlNz09TfXPTWotcl8OX4Kr7Xi1OKebK3bn9rWdUv959B3IEHO4sEhzjP4VWuqtLklXni1V1wobVjcHUkaanql5edijQoE7NJRxSoZhWVsj4/q3rGfnYFpsgMEslscmiWJ4tM4JeC1KgshM+t8JVi560Ml6fuQlbLEtMmEWtfHFcbB5ndboeodgkex3+LNfsnjS1rX/zCuGGwBemq4SE4sn+kTgaOH0Keu5s90XbI1+5wHbQhM9I25NEy2FBwg6XmchwXmxYjffrT4sys2EobL+Xf5TfDGwhRj/0O68yZpCnloHQm2pOD4J8BMKPip06GDg6x7cNwbqH/KiSpCDaLgURtGNpuh0N2jxeCNjgnMrQjz2YXKrQKA57sWNYUMVFeHqgJ5TbnmegTHZFJhblYOT4r+Nbkt4oERLr5dP0D1aOgldBTuaT4awrVF9rcVJSNQM9SuG7pR4YAERsjjHNo3Smqd4D4OYjNkNN03m9+h3krQNQofo1WxGezUaAz6aK+ui9hjbwWQzjhtRc8BuBOMTVY86NVHBGjsEZXtMQIhzD7gULkSMapHLIhaXA9Sw=="
    }
  }
}