apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc-v3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 250Gi