apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc
  labels: 
    recurring-job.longhorn.io/default: enabled
    recurring-job.longhorn.io/remote: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi