# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-config-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: synology-csi-iscsi-delete
#   resources:
#     requests:
#       storage: 100Gi