# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-config-pvc
#   labels: 
#     recurring-job.longhorn.io/default: enabled
#     recurring-job.longhorn.io/remote: enabled
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: synology-csi-iscsi-delete
#   resources:
#     requests:
#       storage: 100Gi