apiVersion: batch/v1
kind: Job
metadata:
  name: scan-movies-job
spec:
  template:
    spec:
      containers:
      - name: scan-container
        image: alpine/curl
        env:
        - name: XPLEXTOKEN
          valueFrom:
            secretKeyRef:
              name: plex-secrets
              key: x-plex-token
        command: ["/bin/sh", "-c", "curl -sS https://peppers.frost.haus/library/sections/1/refresh?X-Plex-Token=$XPLEXTOKEN"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scan-tv-shows-job
spec:
  template:
    spec:
      containers:
      - name: scan-container
        image: alpine/curl
        env:
        - name: XPLEXTOKEN
          valueFrom:
            secretKeyRef:
              name: plex-secrets
              key: x-plex-token
        command: ["/bin/sh", "-c", "curl -sS https://peppers.frost.haus/library/sections/2/refresh?X-Plex-Token=$XPLEXTOKEN"]
      restartPolicy: Never
  backoffLimit: 1