---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-movies
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # Ensure this runs after actual resources are deployed
spec:
  template:
    spec:
      containers:
      - name: scan-container
        image: alpine/curl
        env:
        - name: XPLEXTOKEN
          valueFrom:
            secretKeyRef:
              name: plex-secrets
              key: x-plex-token
        command: ["/bin/sh", "-c", "curl -sS https://peppers.frost.haus/library/sections/1/refresh?X-Plex-Token=$XPLEXTOKEN && echo 'Movies scan triggered successfully.' || echo 'Failed to trigger Movies scan.'"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-tv-shows
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # Ensure this runs after actual resources are deployed
    # argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: scan-container
        image: alpine/curl
        env:
        - name: XPLEXTOKEN
          valueFrom:
            secretKeyRef:
              name: plex-secrets
              key: x-plex-token
        command: ["/bin/sh", "-c", "curl -sS https://peppers.frost.haus/library/sections/2/refresh?X-Plex-Token=$XPLEXTOKEN && echo 'TV Shows scan triggered successfully.' || echo 'Failed to trigger TV Shows scan.'"]
      restartPolicy: Never
  backoffLimit: 1