---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 1Gi