apiVersion: v1
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  # url: https://cd.apps.argoproj.io
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  # dex.config: |
  #   connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: fb563b3a8dd7ea52f683
  #       clientSecret: $argocd-auth:dex.github.clientSecret
  #       orgs:
  #       - name: argoproj
  #         teams:
  #         - argo-rollouts-approvers
  #         - argo-workflows-approvers
  #         - argocd-approvers
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd