replicaCount: 1
name: plex
targetPort: 32400
puid: 1026
pgid: 101
plex-media-server:
  ingress:
    enabled: true
    url: https://peppers.k8s.frost.haus
    ingressClassName: nginx
    certificateSecret: "plex-plex-media-server-ingress-lets-encrypt"
    annotations:
      external-dns.alpha.kubernetes.io/host: peppers.k8s.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - peppers.k8s.frost.haus
        secretName: plex-plex-media-server-ingress-lets-encrypt
  pms:
    configExistingClaim: plex-config-pvc
  extraEnv:
      # This claim is optional, and is only used for the first startup of PMS
      # The claim is obtained from https://www.plex.tv/claim/ is only valid for a few minutes
      PLEX_CLAIM: "claim-TPmFffFTSTTpzpPgPbUj"
      HOSTNAME: "peppers.k8s.frost.haus"
      TZ: "America/Chicago"
      PLEX_UPDATE_CHANNEL: "5"
      PLEX_UID: "1026"
      PLEX_GID: "100"
      ALLOWED_NETWORKS: "0.0.0.0/0"
  extraVolumeMounts:
  - name: arr-media
    mountPath: /data
  extraVolumes:
    - name: arr-media
      nfs:
        server: 192.168.100.250
        path: /volume1/media/library/




