plex-media-server:
  ingress:
    enabled: true
    url: https://peppers.k8s.frost.haus
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/host: peppers.k8s.frost.haus
  pms:
    configExistingClaim: plex-config-pvc
    configStorage: 10Gi
    storageClassName: null
  extraEnv:
      # This claim is optional, and is only used for the first startup of PMS
      # The claim is obtained from https://www.plex.tv/claim/ is only valid for a few minutes
      PLEX_CLAIM: "claim"
      HOSTNAME: "peppers"
      TZ: "America/Chicago"
  #   PLEX_UPDATE_CHANNEL: "5"
  #   PLEX_UID: "uid of plex user"
  #   PLEX_GID: "group id of plex user"
    # a list of CIDRs that can use the server without authentication
    # this is only used for the first startup of PMS
  #   ALLOWED_NETWORKS: "0.0.0.0/0"
  extraVolumeMounts:
  - name: arr-media
    mountPath: /data
    # - /mnt/ramdisk:/transcode
    # - $DOCKERDIR/appdata/plex:/config
    # - "$DOCKERDIR/appdata/plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle:/usr/lib/plexmediaserver/Resources/Plug-ins-f05b712b6/Trakttv.bundle"
    # - /mnt/media/tv:/data/tvshows
    # - /mnt/media/tvdvr:/data/tvdvr
    # - /mnt/media/gphotos/photos:/data/photos
    # - /mnt/media/movies:/data/movies
    # - /mnt/media/filler:/data/filler
  extraVolumes:
    - name: arr-media
      nfs:
        server: 192.168.100.250
        path: /mnt/media





