replicaCount: 1
name: plex
targetPort: 32400
puid: 1026
pgid: 100
plex-media-server:
  image:
    registry: index.docker.io
    repository: plexinc/pms-docker
    tag: "1.41.8.9834-071366d65"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 32400
    metallb.io/ip-allocated-from-pool: first-pool
  ingress:
    enabled: true
    url: https://peppers.frost.haus
    ingressClassName: nginx
    certificateSecret: "plex-plex-media-server-ingress-lets-encrypt"
    annotations:
      external-dns.alpha.kubernetes.io/host: peppers.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - peppers.frost.haus
        secretName: plex-plex-media-server-ingress-lets-encrypt
  pms:
    configExistingClaim: plex-config-pvc
    livenessProbe:
      httpGet:
        path: /identity
        port: 32400
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /identity
        port: 32400
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 5
      failureThreshold: 3
    resources:
      limits:
        memory: 1568Mi
        ephemeral-storage: 16Gi
      requests:
        cpu: 2000m
        memory: 1568Mi
        ephemeral-storage: 16Gi
  extraEnv:
      # This claim is optional, and is only used for the first startup of PMS
      # The claim is obtained from https://www.plex.tv/claim/ is only valid for a few minutes
      PLEX_CLAIM: "claim-TPmFffFTSTTpzpPgPbUj"
      HOSTNAME: "peppers.frost.haus"
      TZ: "America/Chicago"
      PLEX_UPDATE_CHANNEL: "5"
      PLEX_UID: "1026"
      PLEX_GID: "100"
      ALLOWED_NETWORKS: "0.0.0.0/0"
  extraVolumeMounts:
  - name: arr-media
    mountPath: /data
  - name: temp-local-storage
    mountPath: /transcode
  extraVolumes:
  - name: arr-media
    nfs:
      server: 192.168.100.250
      path: /volume1/media/
  - name: temp-local-storage
    emptyDir: {}