plex-media-server:
  ingress:
    enabled: true
    url: https://peppers.k8s.frost.haus
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/host: peppers.k8s.frost.haus
  pms:
    configExistingClaim: plex-config-pvc
  extraEnv:
      # This claim is optional, and is only used for the first startup of PMS
      # The claim is obtained from https://www.plex.tv/claim/ is only valid for a few minutes
      PLEX_CLAIM: "claim-TPmFffFTSTTpzpPgPbUj"
      HOSTNAME: "peppers"
      TZ: "America/Chicago"
  #   PLEX_UPDATE_CHANNEL: "5"
  #   PLEX_UID: "uid of plex user"
  #   PLEX_GID: "group id of plex user"
    # a list of CIDRs that can use the server without authentication
    # this is only used for the first startup of PMS
  #   ALLOWED_NETWORKS: "0.0.0.0/0"
  extraVolumeMounts:
  - name: arr-media
    mountPath: /data
  extraVolumes:
    - name: arr-media
      nfs:
        server: 192.168.100.250
        path: /mnt/media




