replicaCount: 1
name: plex
targetPort: 32400
puid: 1026
pgid: 100
plex-media-server:
  runtimeClassName: nvidia
  image:
    registry: index.docker.io
    repository: plexinc/pms-docker
    tag: "1.42.1.10060-4e8b05daf"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 32400
    metallb.io/ip-allocated-from-pool: first-pool
  ingress:
    enabled: true
    url: https://peppers.frost.haus
    ingressClassName: nginx
    certificateSecret: "plex-plex-media-server-ingress-lets-encrypt"
    annotations:
      external-dns.alpha.kubernetes.io/host: peppers.frost.haus
      cert-manager.io/cluster-issuer: letsencrypt
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Media Server
      gethomepage.dev/group: Media
      gethomepage.dev/icon: plex.png
      gethomepage.dev/name: Plex
      gethomepage.dev/widget.type: "plex"
      gethomepage.dev/widget.url: "https://peppers.frost.haus"
      gethomepage.dev/weight: "10"
    tls:
      - hosts:
          - peppers.frost.haus
        secretName: plex-plex-media-server-ingress-lets-encrypt
  pms:
    gpu:
      nvidia:
        enabled: false
    configExistingClaim: plex-config-pvc
    livenessProbe:
      httpGet:
        path: /identity
        port: 32400
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /identity
        port: 32400
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
      failureThreshold: 3
    resources:
      limits:
        memory: 2Gi
        ephemeral-storage: 64Gi
        nvidia.com/gpu: "5"
      requests:
        cpu: "2"
        memory: 2Gi
        ephemeral-storage: 64Gi
        nvidia.com/gpu: "5"
      affinity:
      claimSecret:
        name: "plex-secrets"
        key: "plex-claim"
  extraEnv:
      HOSTNAME: "peppers.frost.haus"
      TZ: "America/Chicago"
      PLEX_UPDATE_CHANNEL: "5"
      PLEX_UID: "1026"
      PLEX_GID: "100"
      ALLOWED_NETWORKS: "0.0.0.0/0"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      CUDA_DRIVER_CAPABILITIES: compute,video,utility
  extraVolumeMounts:
  - name: arr-media
    mountPath: /data
  - name: temp-local-storage
    mountPath: /transcode
  extraVolumes:
  - name: arr-media
    nfs:
      server: 192.168.100.250
      path: /volume1/media/
  - name: temp-local-storage
    emptyDir: {}