apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sabnzbd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: sabnzbd.frost.haus
spec:
  tls:
  - hosts:
    - sabnzbd.frost.haus
    secretName: sabnzbd-cert
  rules:
  - host: sabnzbd.frost.haus
    http:
      paths:
      - path: /
        backend:
          serviceName: sabnzbd
          servicePort: 80