replicaCount: 1
name: pihole
targetPort: 8989
pgid: 1000
puid: 1000
ingress:
  enabled: true
  hosts:
  - dns1.k8s.frost.haus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: dns1.k8s.frost.haus
pihole:
  dnsmasq:
    customSettings:
      - name: DNSMASQ_LISTENING=
        value: all
    customDnsEntries:
      - address=/dns1/192.168.100.20
    customCnameEntries:
      - cname=dns1.brainboy.local.lan,dns1.k8s.frost.haus
  persistentVolumeClaim:
    enabled: true
  podDnsConfig:
    enabled: false
  serviceWeb:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDns:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDhcp:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    port: 67