replicaCount: 1
name: pihole
targetPort: 8989
pgid: 1000
puid: 1000
ingress:
  enabled: true
  hosts:
  - dns1.k8s.frost.haus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: dns1.k8s.frost.haus
pihole:
  capabilities:
    add:
    - SYS_TIME
    - SYS_NICE
  adlist:
    enabled: true
    list:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://blocklistproject.github.io/Lists/alt-version/porn-nl.txt
      - https://small.oisd.nl
      - https://nsfw.oisd.nl
  monitoring:
    podMonitor:
      enabled: true
  dnsmasq:
    # customSettings:
    #   otherSettings: |-
    #     DNSMASQ_LISTENING=all
      # DHCP_START=/192.168.100.100/
      # DHCP_END=192.168.100.200
      # DHCP_ROUTER=192.168.100.1
      # DHCP_LEASETIME=24
      # PIHOLE_DOMAIN=brainboy.local.lan
      # DHCP_IPv6=false
      # DHCP_rapid_commit=false
      # DHCP_ACTIVE=true
      # BLOCKING_ENABLED=false
      # ADMIN_EMAIL=bfrost@brainboy.com
      # WEBUIBOXEDLAYOUT=boxed
      # WEBTHEME=default-light
      # PIHOLE_INTERFACE=wlan0
      # IPV4_ADDRESS="192.168.100.21/24"
      # IPV6_ADDRESS=""
      # QUERY_LOGGING=false
      # INSTALL_WEB_SERVER=false
      # INSTALL_WEB_INTERFACE=true
      # LIGHTTPD_ENABLED=true
      # CACHE_SIZE="10000"
      # DNS_FQDN_REQUIRED=true
      # DNS_BOGUS_PRIV=true
      # DNSSEC=false
      # REV_SERVER=false
      # REV_SERVER_CIDR=192.168.100.0/16
      # REV_SERVER_TARGET=192.168.100.21
      # REV_SERVER_DOMAIN=brainboy.local.lan
      # TEMPERATUREUNIT=C
      # PIHOLE_DNS_1=127.0.0.1#5335
      # PIHOLE_DNS_2=""
    customDnsEntries:
      - address=/super-duke.brainboy.local.lan/192.168.100.250 
    additionalHostsEntries:
      - 192.168.100.20 dns1.brainboy.local.lan
      - 192.168.100.21 dns2.brainboy.local.lan
      - 192.168.100.114 birdnet.frost.haus
      - 192.168.100.1 router.brainboy.local.lan
      - 192.168.100.134 pepper.brainboy.local.lan
# 192.168.100.173 homeassistant.brainboy.local.lan
# 192.168.100.50 argocd.frost.haus
# 192.168.100.50 guestbook.frost.haus
# 192.168.100.50 dashboard.frost.haus
# 192.168.100.50 longhorn.frost.haus
# 192.168.100.50 sonarr.k8s.frost.haus
# 192.168.100.50 kube-prometheus-stack.k8s.frost.haus
# 192.168.100.50 prometheus.k8s.frost.haus
# 192.168.100.50 grafana.k8s.frost.haus
# 192.168.100.50 radarr.k8s.frost.haus
# 192.168.100.50 sabnzbd.k8s.frost.haus
# 192.168.100.50 radarr-exporter.k8s.frost.haus
# 192.168.100.50 alertmanager.k8s.frost.haus
# 192.168.100.50 dozzle.k8s.frost.haus
# 192.168.100.50 boilerplate.k8s.frost.haus
# 192.168.100.50 prowlarr.k8s.frost.haus
# 192.168.100.50 peppers.k8s.frost.haus
# 192.168.100.50 overseerr.k8s.frost.haus
# 192.168.100.50 pihole.k8s.frost.haus
# 192.168.100.2 switch.frost.haus
# 192.168.100.221 pve1.frost.haus
# 192.168.100.222 pve2.frost.haus
# 192.168.100.223 pve3.frost.haus
# 192.168.100.249 pbs.frost.haus
    customCnameEntries:
      - cname=dns1.brainboy.local.lan,dns1.k8s.frost.haus
  persistentVolumeClaim:
    enabled: true
  podDnsConfig:
    enabled: false
  serviceWeb:
    adminPassword:
      useSecret: true # Enable using a secret
      secretName: pihole
    type: LoadBalancer
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDns:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDhcp:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    port: 67
  doh:
    enabled: true
    pullPolicy: Always
    envVars: {
      DOH_UPSTREAM: "https://1.1.1.1/dns-query"
    }