replicaCount: 1
name: pihole
targetPort: 8989
puid: 1026
pgid: 100
pihole:
  capabilities:
    add:
    - NET_ADMIN
    - SYS_TIME
    - SYS_NICE
  monitoring:
    podMonitor:
      enabled: true
  persistentVolumeClaim:
    enabled: true
    existingClaim: "pihole-config-pvc"
  podDnsConfig:
    enabled: false
  admin:
    adminPassword:
    useSecret: true
    passwordKey: password
    existingSecret: pihole
  serviceWeb:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDns:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDhcp:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    port: 67