replicaCount: 1
name: pihole
targetPort: 8989
pgid: 1000
puid: 1000
ingress:
  enabled: true
  hosts:
  - dns1.k8s.frost.haus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: dns1.k8s.frost.haus
adlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://blocklistproject.github.io/Lists/alt-version/porn-nl.txt
  - https://small.oisd.nl
  - https://nsfw.oisd.nl
blacklist: []
dnsmasq:
  staticDhcpEntries:
    - dhcp-host=7C:78:B2:0D:E3:9A,192.168.100.109,front-door-wyze
    - dhcp-host=C8:2B:96:03:3E:A1,192.168.100.127,Inkbird
    - dhcp-host=40:F5:20:28:84:BF,192.168.100.159,wled-eli
    - dhcp-host=34:94:54:25:1D:78,192.168.100.184,wled-square
    - dhcp-host=CE:3A:1C:73:B7:0E,192.168.100.158,phrosty
    - dhcp-host=E4:5F:01:00:2B:A5,192.168.100.114,birdnetpi1
    - dhcp-host=5C:A6:E6:95:DC:BE,192.168.100.101,LR-Switch
    - dhcp-host=9C:8E:CD:2C:21:DD,192.168.100.170,front-door-camera
    - dhcp-host=40:F5:20:27:8C:3A,192.168.100.113,wled-swizzle
    - dhcp-host=D8:28:C9:51:30:AE,192.168.100.180,GEFridge
    - dhcp-host=E8:DB:84:99:5F:36,192.168.100.196,wled-cr-10
    - dhcp-host=4C:75:25:AF:2C:28,192.168.100.130,wled-matrix
    - dhcp-host=BC:FF:4D:19:1D:8E,192.168.100.103,wled-bar
    - dhcp-host=A0:B7:65:64:3A:50,192.168.100.125,esp32-bluetooth-relay
    - dhcp-host=9C:8E:CD:1C:24:99,192.168.100.129,yard_cam
    - dhcp-host=5C:C3:36:56:6D:46,192.168.100.162,BnB-living-room-cam
    - dhcp-host=44:A5:6E:4D:3B:91,192.168.100.100,orbi-upstairs
    - dhcp-host=94:83:C4:18:4A:9D,192.168.100.199,MT1300
    - dhcp-host=9C:8E:CD:1C:22:11,192.168.100.193,door-camera
    - dhcp-host=BC:FF:4D:19:25:32,192.168.100.104,wled-cr
    - dhcp-host=48:E7:29:C8:F6:A8,192.168.100.133,wled-eg-table
    - dhcp-host=40:F5:20:27:08:71,192.168.100.135,wled-eg-desklamp2
    - dhcp-host=84:CC:A8:9F:AD:76,192.168.100.117,wled-eg-desklamp1
    - dhcp-host=BC:24:11:45:53:CF,192.168.100.137,k8s-n1
    - dhcp-host=BC:24:11:A8:67:A8,192.168.100.175,k8s-c1
    - dhcp-host=60:83:E7:43:3F:A4,192.168.100.99,UpstairsArcher
    - dhcp-host=4C:75:25:AF:26:D4,192.168.100.105,wled-m5-ring
    - dhcp-host=6C:4A:85:9C:92:92,192.168.100.187,BethIPAD
    - dhcp-host=BC:24:11:31:F4:CD,192.168.100.139,k8s-n2
    - dhcp-host=BC:24:11:0C:41:C2,192.168.100.145,k8s-n3
    - dhcp-host=DC:A6:32:D5:5B:F0,192.168.100.195,octopi
    - dhcp-host=02:BE:CF:B7:C5:8D,192.168.100.173,homeassistant
    - dhcp-host=FC:E8:C0:F8:47:7F,192.168.100.121,SLZB-06P10
pihole:
  dnsmasq:
    upstreamServers: []
    additionalHostsEntries:
      - 192.168.100.20 dns1.brainboy.local.lan
      - 192.168.100.21 dns2.brainboy.local.lan
      - 192.168.100.114 birdnet.frost.haus
      - 192.168.100.1 router.brainboy.local.lan
      - 192.168.100.134 pepper.brainboy.local.lan
      - 192.168.100.173 homeassistant.brainboy.local.lan
      - 192.168.100.50 argocd.frost.haus
      - 192.168.100.50 guestbook.frost.haus
      - 192.168.100.50 dashboard.frost.haus
      - 192.168.100.50 longhorn.frost.haus
      - 192.168.100.50 sonarr.k8s.frost.haus
      - 192.168.100.50 kube-prometheus-stack.k8s.frost.haus
      - 192.168.100.50 prometheus.k8s.frost.haus
      - 192.168.100.50 grafana.k8s.frost.haus
      - 192.168.100.50 radarr.k8s.frost.haus
      - 192.168.100.50 sabnzbd.k8s.frost.haus
      - 192.168.100.50 radarr-exporter.k8s.frost.haus
      - 192.168.100.50 alertmanager.k8s.frost.haus
      - 192.168.100.50 dozzle.k8s.frost.haus
      - 192.168.100.50 boilerplate.k8s.frost.haus
      - 192.168.100.50 prowlarr.k8s.frost.haus
      - 192.168.100.50 peppers.k8s.frost.haus
      - 192.168.100.50 overseerr.k8s.frost.haus
      - 192.168.100.50 pihole.k8s.frost.haus
      - 192.168.100.2 switch.frost.haus
      - 192.168.100.221 pve1.frost.haus
      - 192.168.100.222 pve2.frost.haus
      - 192.168.100.223 pve3.frost.haus
      - 192.168.100.249 pbs.frost.haus
    customCnameEntries:
      - cname=dns1.brainboy.local.lan,dns1.k8s.frost.haus
    # customSettings:
    #   otherSettings: |-
    #     DNSMASQ_LISTENING=all
    #     DHCP_START=/192.168.100.100/
    #     DHCP_END=192.168.100.200
    #     DHCP_ROUTER=192.168.100.1
    #     DHCP_LEASETIME=24
    #     PIHOLE_DOMAIN=brainboy.local.lan
    #     DHCP_IPv6=false
    #     DHCP_rapid_commit=false
    #     DHCP_ACTIVE=true
    #     BLOCKING_ENABLED=false
    #     ADMIN_EMAIL=bfrost@brainboy.com
    #     WEBUIBOXEDLAYOUT=boxed
    #     WEBTHEME=default-light
    #     PIHOLE_INTERFACE=wlan0
    #     IPV4_ADDRESS="192.168.100.21/24"
    #     IPV6_ADDRESS=""
    #     QUERY_LOGGING=false
    #     INSTALL_WEB_SERVER=false
    #     INSTALL_WEB_INTERFACE=true
    #     LIGHTTPD_ENABLED=true
    #     CACHE_SIZE="10000"
    #     DNS_FQDN_REQUIRED=true
    #     DNS_BOGUS_PRIV=true
    #     DNSSEC=false
    #     REV_SERVER=false
    #     REV_SERVER_CIDR=192.168.100.0/16
    #     REV_SERVER_TARGET=192.168.100.21
    #     REV_SERVER_DOMAIN=brainboy.local.lan
    #     TEMPERATUREUNIT=C
    #     PIHOLE_DNS_1=127.0.0.1#5335
    #     PIHOLE_DNS_2=""
    customDnsEntries:
      - address=/super-duke.brainboy.local.lan/192.168.100.250 
  whitelist: []
  capabilities:
    add:
    - SYS_TIME
    - SYS_NICE
  monitoring:
    podMonitor:
      enabled: true
  persistentVolumeClaim:
    enabled: true
  podDnsConfig:
    enabled: false
  admin:
    adminPassword:
    useSecret: true # Enable using a secret
    passwordKey: password
    existingSecret: pihole
  serviceWeb:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDns:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDhcp:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "key-192.168.100.20"
    loadBalancerIP: 192.168.100.20
    externalTrafficPolicy: Cluster
    port: 67
  doh:
    enabled: true
    pullPolicy: Always
    envVars: {
      DOH_UPSTREAM: "https://1.1.1.1/dns-query"
    }