replicaCount: 3
name: pihole
targetPort: 8989
pgid: 1000
puid: 1000
ingress:
  enabled: true
  hosts:
  - dns1.k8s.frost.haus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: dns1.k8s.frost.haus
pihole:
  dnsmasq:
    customDnsEntries:
      - address=/dns1/192.168.100.20
    customCnameEntries:
      - cname=dns1.brainboy.local.lan,dns1.k8s.frost.haus
      - cname=dns1.brainboy.local.lan,dns1
  persistentVolumeClaim:
    enabled: true
  serviceWeb:
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  serviceDns:
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    externalTrafficPolicy: Cluster
    https:
      enabled: true
      port: 443
  podDnsConfig:
    enabled: false
  serviceDhcp:
    loadBalancerIP: 192.168.100.20
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    externalTrafficPolicy: Local
    port: 67