apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
  annotations:
    external-dns.alpha.kubernetes.io/hostname: guestbook.frost.haus
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  type: LoadBalancer
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: guestbook-ui
