---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: poterie-admin
  namespace: poterie
spec:
  encryptedData:
    ADMIN_PASS: AgAJsMhbulD4iKaN193dY7A7o5HTXauTsh2Zd/3Qy1yHxQfZY2WDmOweRG9i7SRoPtmHyWMg55EMwdlP7ICo8b3PJNUTUlbhEOkpK/2SsC6QQCCbHSN0iQfLiw+01QnAyKexZUkvS2bAkJIWTkzh8DvtbVmOtfYpBSLk9TAtWU9M9q/NRe/0DOLF2aUzNA4wIeZ7IKBH35MeorQI+NjjSylKKeqny4kB7jr+0pYUd6EPntFKH53u+OissdiJg4fjWHogoT9bq5B2lbKKCAyHVI792LwGgozxRjXycLMUtAMCBlvWibfzysLJqw2kMVjP9W5ZFTxIg12IlO0xu1C3x7LNYNFQI2K2cUYGtI8IwiE/jXJSodPo37GrW/j1TprITxrZJ3ibNSPkkgXnK3++97VTwcWerr4Ty2FHbRVzGmZvOV/hbjvPQJJblWmCTbfteVmPz7npXhPwI/LFbRQf6WfpgzBW3YJ2pfzUxw4IA+LvOryMMb4jzB52YL3KT0HAJtPmMiRjE7tSi4gVaYpPtMgGZkZ1u0EqJBu3nOCjLGcTSMkcIr641DqFCLfZZMtrzobZqwLdf5EnrVZmfdI7OZhbdn78LnydvL/rpbKWVGvMj1QXm3N9/DGlkFGd9maXIthCczmsv0b2Arihhng03Mycl9OTKtLUooB80rOTuogiI4F3cclCmm0AfRQnUGdUhVJAdPzKnyVP8tU=
    ADMIN_USER: AgBDgKHtnEICRTV4LJalq5dYpLjAHtQQe1OzvdAk56Me4n7yoc9Hhfyc65qCTXPS4fMdnB87hO0KbavcB7YwMk7YoHVQ74NNZc7zpxaKGFRvHIEzg3CmUTpeolnAq5Nqh0tf9+WMp0Av/YX/D0sOKpc297pRYvkR5EV1JFdiyTIyjtk0TeEp8QPDQiOKVyWwa70mzigYO7DAVtk/0IGeAJ+OHVD1Q2GafRerP6btDRE4v5NJwgKElxGCVKowRzn8m+UrHisnWFgX6xc/pbA5BHGg9hkqg2C0GjTErh6IbfAyPLRyqSwcLKaxC2VdU9bjZXiyQmhC5axndggB518MDWXDfYI+T4XGcLo3ISQel6dXsLWzfgZ5OitmIgQLEUD4fvoiO0SUAl0SPPTROU+thNjTcJTIaoZpXWXvB1k3hZ47rY5cLs2V+byuYdOW1N6OeT6tKiqL2e1RWSrkNJtTxF8M8GkOyeVsmf3hNPUflv5l6Spc76JRnBTZNPO5d42v+cyUmrXFFJBVJiKNJBqd/ISypZpdEQ3Fo2yx0vBOEcPY7+NZI6IlDGqH3CncBbHOk/LwiXho1QThITYYo+VqwiUVkCzOYzJ86Z02GsROp86a1LUaatAi6weXHvvcjY+YJxWCGGAcmrTjPKS1CRUqkr6vDWqC9qPXnvk3xZNXl3tR3GFSz3AMpbNTUxAuQumPWivXTvF3MQ==
  template:
    metadata:
      name: poterie-admin
      namespace: poterie
