apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-flannel
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/flannel
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision:  {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    managedNamespaceMetadata:
      labels:
        argocd-managed: true