apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-servarr
  namespace: argocd
spec:
  source:
    path: charts/mcp-servarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: mcp-servarr
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    managedNamespaceMetadata:
