apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebula-sync
  namespace: argocd
spec:
  source:
    path: charts/nebula-sync
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision:  {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nebula-sync
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    managedNamespaceMetadata:
