---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgA9Fadg3DaECyPTw5gc5C8f5M0DQ+dMXWnpOI9/2K6jr6qOLqgNTYlTO1li97p4Bb04SyXL8WbjnjijIzy/dMAIarlH4tosRTL/SbTrp9z3DjDi05Qo3IbF3tB0bLYW3vXePZULvfIA836ntCJcVvr8Sljy91/6yBpqhHQFPdB9UG2oJESh2bpx+HWHSHLOHmkRJ4V/I0aeBjm1DTHLoHIeUhc4DGNuiyECBZ9RmP1n/6Ohhq+8Uc4tq3Lqhm9o8ulU6VT7gXyErC1VbEzWWtbMOq2NtcQYJcdVG105139OjJSwVN6JXQI74REz825Q5ZBcL/biCLSnU8HRP3QRq8EeHhy67DlzWwUeJtU8FUSICXc4HTH78p+4GAFm8q5rP61ByiUeMCoLDV8lXm07GKjysRk5OzEv+ITcjRuxEDjBWxAfDzXp7sLLZxDkQtrxG0pLADPnJuv9BCdKau5XZ3ezq6kB5kyIubfTaZR06mVQVlEbH1Gp/yVh/g8xDh1E8cLOQELCAvPSi+RPTK2p3B2awiGxHoTS49OpNVlQ8B9unnwWRihiSKd1eEbFGWsNRPzzOaFZUKcNVVLVOu6mYlhv+vA/T0vf/vqkwR2hQeaPTIdy/Tx2OQku7i2XzHMdgyoQyWaeLgSIHK9AYJkxV5Mb4ReevEroWdlSxp6dVBnP1yVTvk1SK0HnIhIYSjJ0Eq0CaQjlGyJhrfpKPgBvjOdt4a8G//YacmCpLiKYLoHclElyB5Zhdb1c+wCE+70dc8/8umfiSw==
  template:
    metadata:
      name: cloudflare-credentials
      namespace: external-dns
