external-dns:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag:  ""
  pullPolicy: IfNotPresent  # @schema enum:[IfNotPresent, Always]
  # TODO: uncomment and configure cloudflare provider
  provider: cloudflare
  # cloudflare:
  #   secretKey: api-key
  #   email: your@email.com
  # policy: sync
  policy: upsert-only
  sources:
    - ingress
    - service
  # registry: "txt"
  # txtOwnerId: frost-haus
  domainFilters:
    # - ".k8s.brainboy.local.lan"
  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 10m
  ## ensure RBAC is enabled
  rbac:
    create: true
    apiVersion: v1
  logLevel: debug
  # logLevel: info
