external-dns:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag:  ""
  pullPolicy: IfNotPresent  # @schema enum:[IfNotPresent, Always]
  provider: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-credentials
          key: cloudflare_api_token
  policy: upsert-only
  sources:
    - ingress
    - service
  domainFilters:
    - "frost.haus"
  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 10m
  ## ensure RBAC is enabled
  rbac:
    create: true
    apiVersion: v1
  logLevel: debug
