external-dns:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag:  ""
  pullPolicy: IfNotPresent  # @schema enum:[IfNotPresent, Always]
  provider: rfc2136
  domainFilters:
    - frost.haus
  policy: upsert-only
  sources:
    - ingress
    - service
  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 10m
  ## ensure RBAC is enabled
  rbac:
    create: true
    apiVersion: v1
  logLevel: debug
  env:
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      valueFrom:
        secretKeyRef:
          name: external-dns-technitium
          key: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
      value: "external-dns"
  extraArgs:
    - --rfc2136-host=192.168.100.41
    - --rfc2136-port=53
    - --rfc2136-zone=frost.haus
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-axfr
