---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synology-csi
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgBofvWQZzsYwkucXw26v6P62qZBFpc/HRLkjGrqj0vm4IkkMMUGExyRiymvofl90Wk8HoBJJDIQIE9oT2YVs25450DFuAXB66YJNMhL9L0aiduJaQ1XR8+jYZ4te2famR3sA2mxH/VmNh1FlTuFOQEmgCMSEtj721ndKVSc4EQQAbc+9NxsqbhptOGRptIgQ2SA9jQLpbzEk/kZRy8aC/GCS36oLMXXtwIeplg4A3uW+tJWGoLatwj9v9tkddM4agi7372upAijk1tric9hpnlmtsc5FPpZETqBLxjeNFBp2d07Ma3NXHqIOoX9Bs37h6LnqJS+JVhmfYn1C9u3Bi+NuzWX97o3siUyTnj+HxdJgvRY9hWFZl0sUkNmsc7fURWbY+g9pVLf3ZzK117G00McrDNIuMBmLVzyduUU+uiFumLLsVXZuD2YlIQDQCOd9mheJ16qOCbxLihXqIvdIquh8AY+DLwpJS2AD0jn11iZ9336W4GKNfiwHC8Z7cMOfWcg8ab+eCECdpoV5esUTyHdBgJXxXrJmg7FSgE8pK5tim3HPWkdGr/E/5F3nv/sM6nQAP7UiQTMpZRDkcJUPSusf0pshi0zySWyGtNUb6QND0NKnl8flEXq6MNp4i3bDAZZr8I6zBFRAQVARFucBxKUpYfkS2krgjwBR8PDvmB/8xzbFwSNAUe62Q2Elre2cZ1takwtMd0tb63u7EgO1hIFk73nb1PMRwN4x+jfOq8g+9aXZeS8GN+IW8uzmVr5EJLNUlo1DU+nFlodlw2d0rxUTHZVweJ6gisAUHjOOPaz/0MAlDCY1oerAjpYkr/Fywt52AbCeUYb4JNJROq0m/IaB5gt4kN2GK2Qnd4=
  template:
    metadata:
      creationTimestamp: null
      name: synology-csi
      namespace: synology-csi
