---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syno-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 1Mi