---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: https://sonarr.frost.haus
        api_key: !env SONARR_API_KEY
        quality_definition:
          type: series
        include:
          # Anime
          - template: sonarr-quality-definition-anime
          - template: sonarr-v4-quality-profile-anime
          - template: sonarr-v4-custom-formats-anime
          # WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p
          # WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p
        custom_formats:
          - trash_ids:
              - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
            assign_scores_to:
              - name: WEB-1080p
                score: 0
          - trash_ids:
              - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
            assign_scores_to:
              - name: WEB-1080p
          - trash_ids:
                - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
                - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
              assign_scores_to:
                - name: WEB-2160p
          - trash_ids:
              - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
            assign_scores_to:
              - name: WEB-2160p
                score: 0
          - trash_ids:
              - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
            assign_scores_to:
              - name: WEB-2160p
          - trash_ids:
              - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
            assign_scores_to:
              - name: WEB-2160p
          - trash_ids:
              - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
            assign_scores_to:
              - name: WEB-1080p
                score: 0
          - trash_ids:
              - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
            assign_scores_to:
              - name: WEB-1080p
          - trash_ids:
              - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired
          - trash_ids:
              - b2550eb333d27b75833e25b8c2557b38 # 10bit
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired
          - trash_ids:
              - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 100 # Adjust scoring as desired
    radarr:
      instance1:
        # Set the URL/API Key to your actual instance
        base_url: https://radarr.frost.haus
        api_key: !env RADARR_API_KEY
        quality_definition:
          type: movie
        include:
        # WEB-1080p
        - template: radarr-quality-definition-movie
        - template: radarr-quality-profile-remux-web-1080p
        - template: radarr-custom-formats-remux-web-1080p
        # WEB-2160p
        - template: radarr-quality-definition-movie
        - template: radarr-quality-profile-remux-web-2160p
        - template: radarr-custom-formats-remux-web-2160p
        # Anime
        - template: radarr-quality-definition-anime
        - template: radarr-quality-profile-anime
        - template: radarr-custom-formats-anime
        custom_formats:
          - trash_ids:
              - 0f12c086e289cf966fa5948eac571f44 # Hybrid
              - 570bc9ebecd92723d2d21500f4be314c # Remaster
              - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
              - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
              - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
              - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
              - 957d0f44b592285f26449575e8b1167e # Special Edition
              - eecf3a857724171f968a66cb5719e152 # IMAX
              - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
            assign_scores_to:
              - name: Remux + WEB 1080p
          - trash_ids:
              - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
            assign_scores_to:
              - name: Remux + WEB 1080p
                score: 0
          - trash_ids:
              - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
            assign_scores_to:
              - name: Remux + WEB 1080p
          - trash_ids:
              - 0f12c086e289cf966fa5948eac571f44 # Hybrid
              - 570bc9ebecd92723d2d21500f4be314c # Remaster
              - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
              - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
              - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
              - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
              - 957d0f44b592285f26449575e8b1167e # Special Edition
              - eecf3a857724171f968a66cb5719e152 # IMAX
              - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
            assign_scores_to:
              - name: Remux + WEB 2160p
          - trash_ids:
              - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
            assign_scores_to:
              - name: Remux + WEB 2160p
                score: 0
          - trash_ids:
              - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
            assign_scores_to:
              - name: Remux + WEB 2160p
          - trash_ids:
              - 9c38ebb7384dada637be8899efa68e6f # SDR
            assign_scores_to:
              - name: Remux + WEB 2160p
          - trash_ids:
              - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired
          - trash_ids:
              - a5d148168c4506b55cf53984107c396e # 10bit
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired
          - trash_ids:
              - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 100 # Adjust scoring as desired