---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:latest
              imagePullPolicy: Always
              tty: true # for color support
              env:
              - name: SONARR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: configarr
                    key: SONARR_API_KEY
              - name: RADARR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: configarr
                    key: RADARR_API_KEY
              volumeMounts:
                - mountPath: /app/repos
                  name: {{ .Values.name }}-config-pvc
                  subPath: configarr-repos
                - name: config-volume
                  mountPath: /app/config/config.yml
                  subPath: config.yml
          volumes:
            - name: {{ .Values.name }}-config-pvc
              persistentVolumeClaim:
                claimName: {{ .Values.name }}-config-pvc
            - name: config-volume
              configMap:
                name: configarr
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 2Gi