---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: release-notify-webhook
  namespace: configarr
spec:
  encryptedData:
    webhook-url: AgCwiWR7qKz6CUUwffk0m/H/Us8pDlUjaW2Y4z6MFP9XGpOyzVuycBK1+dsGQeontVgCtsaxOLrrQDxYyrNeKZQDYZ3hWNLs3rktVEyd7TS4K4zkT8HKbsXSRNny9hBJJuIis8JA7o4MZ+PpnXMDqcEsEX//JgGzN4b/szjbr+lMa5rBaQ1OVwvsmf7CRD+Ot1QNAVE1ZDJxSA0YQcx3H9J+JuxvCVJD0cchlHSPM1PxIZSlGYlQQNAxeQ4Caq3MqSpgqYvCaNN4VOonRPUHyK2w4hA7chhpJh6ZmQ/J7f1zZZsNVsnSPgWXu17sZgTlI85GU5tXb3j8Bvud2pOYPiEDz+xzGy5MyabXBFiXL5mkZMkjgn+MKT1vKnTL0sbDWppDDAe8wR8wnynJz8VUg5qmSvRRRTLbwaQ4kw3ob3OPBKDf1x+8060mNGgs+fB6YO11nnsYTasPnUrVPdEhjZX0MoNNKY6m6aMv6dsKt/wNdknl2glcFMlHMg67Yv6jE7c7X6/mc8aPg5WdmydkTDKoQEesE7M1HSAZ+D2/APfd8A2axGnhPRW5nCIjDRlrq1+owJi+5aVMNp0x8XpoPjgvY8C990GlkQUZeSB64ccD6ip2JbK3GXYvHFN/VM5wHG9w+42UIHJSgv/XuhCFOsesHa9RUf+BNOm/xVM48RMGwlhXIDN5MLRiUTKEGcVFXWs2XJyBpXoyQqGJ1ZzYlf0n5cUSFcyWMB02RwQL8UKUPFXM4po8P0xrV7yasdtkB6UEK2XHfi9Atm2NT1hJmDEYfpqr2dvojNh+JqOTRg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: release-notify-webhook
      namespace: configarr
