---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: configarr
  namespace: configarr
spec:
  encryptedData:
    RADARR_API_KEY: AgCT1VqX4wPXibUBAuAP4W/aROTMTTBeyuHj+4lNesUpOnLY9+ehk6U3EpAM/fLG6sRhXHUZOeMRF+Vmh0LZhHLcR5GDlVtPL2pFIlXrg2GnDY4zFLpo7SrdDPyN76/DAA+l3/aGQiLc4fs+07x7RemCH/Vm/d30HbLS5Kk+k7YuMB6BZAQRFNi76kI4m9kEjDMzlsGuUCScm9mBE8gQPuPpO58zK+FwCXhCqDmSgMsQQiK5RagSJOecRupZHrJA/sZVuRjGMgoPx6z/3FTKimCGSIsmnxaO0/8bkHMK3qx0M9PAY5l9pZtUSPvu4LJDKWim4JPOwqx3MoOmmxove/7sAfuRVxbOMSgm110gN7Qz/vTrnAdjI1wahhJ/N9M6P7iwB04IKbsGkeAn0NUng7BZi3IGlWiVlAMByLSKSB65CPMTrScw1JpB9kfwF4sOoJr3YDSSm3SlVcBHk8vsYnR9hk3oET7E+StWLVYOWsii6LoAE6BRcmku0mEpnnWKm26KLMkl2faEWzF13iPmHUW1qR9LIeTrow9I7uBwHFh/ycH/yMJZQ9rzGc4T8XWtjyww8gcMImaa99Ig8GeRBVKhO1igPotWQ4l4UFp4DICOrqLgd5XJ4BTTN7pV5Hcs6X/goK0b/KwHgflINvNrRzF8dHIRHVwIa3XWe8/wrp9hWvzzj2QfVxGc8jhib/aHpr7j33r1C9NVijpsyMVX/jNNSgYBtLL74i6WsLY78XGv9A==
    SONARR_API_KEY: AgCdKzoIHKym2U4hhVamL+op4Jwvg92QwSR66jD6rJ07ThDMuhutmBXSHP/PZZvFbbfnMRk2oABCn5oSlEYOhWHRxmADHwEcHRr3EJUJzk+SHrtwsKD+vaH8QFKoQD0AGtCZzUwIev6KmpsgujM9cD3RVFuUR5JLnvqCDzFUrfjAR0eNAdiPi3o51u5k1KRNlydbLLwHWM9/r/R7XcqbeafdxfgXLuRXZCShnFDmrbZ7CpAeIMyQ11AsOSZ9a0ebf7JObDfxLbWKODXU/vLQgKnA68K9lPPWiQbsPVnLsPprxV74AgP4H9Fyhch1RjajHKDnkvk01mhxFs5VrK5bQ8eqJmXtKmWznrq+SJnjFCx21CUbGO/sfiKj5/aB5Oms7yOtBQI0YntFii9OSJ+mcJj5hj4mZQxjcNRkErNGdwAFlfESxj0Ia/jX6mEHD8zliR4CqpY9l2lVnnOMsE+1F5Tz6sbbuaxnFdZaeyrioHjKvQTtR/oPWXWKF5CQWuBLFBBie+tpp8QSm2ivjwNZZUH3UYMwOC1Y7HpKopj+LtE8hk/+JGUjGhXVvT8jADGeIwv258rCn0g1+CTG6O6+dF3DtDn4GEtUxEbJ5lLhK/XpJen/i5sk9axqy8WRdnXeqIuy2fTuzK2PuH5aWqFsc0tjuSDNqY09bnJYaxPwQsdgaU7MVWDp+RZWHrsjTPXmsnALmuE/OcpVieJyA10Rn0XbhfsLc3rPIrBg0+iT8nj4bso=
  template:
    metadata:
      creationTimestamp: null
      name: configarr
      namespace: configarr
