---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: release-notify-webhook
  namespace: configarr
spec:
  encryptedData:
    webhook-url: AgA7kj5e7Y9f5puO+6azETq24v9HOew5TK1/Q0aSUdRKrDBkWk3ql0WPAoyTekV5NXVDCvsNX2mm4LxxYULgHnznXXl+QLY/8iXNg1Qy66baf9MkJE/jNZw8Q4RN5U/dFx2xMrDqCu5RfuHDpGqWnxhrufwJkHmLBbBDRz4+bf+sAPfk3tVQRO66v7O6Oxze4GhkHDSBDjyA6GaI3VJS4VIpce62Kifg54/JYPM5C3WQDa0qoAmxm5+UQ7MocoJpAmCFZ9ttZEE4/7vtVwi9UYNLkgpTjtjRSgH2uT2Fy+g7K0Ly6LpJ9+rk4rhJtx8Ns9qfW2DLDDmblzVPE2UwTZ2xdfRTrQhZ9aRQKt2LB9+5PKwL49F+QDR+CnyGZVXTSlS8cgmMT7KN27/E0rUUFQ2Hui3N/0XOVjOhkpUfGMC8SDGW7lPGqtSzWafCrIddJ6OQY9fANKTCva8LNT6mBoRGJ6Hvw/cG3a6Q7ZV6BNFLE5UDQ/iRcs7t/e08+E5oArRgoRQtOIPxe+QHRP53Z1WbUv2YLaYkFVBLjgEDCB7pFJ2HtfO8VOuCkDdNBI0xH2n9r4Z1GsCp62C7qNQcIblwoVRqixorYUfBwkjm8IBMOCdOv5CTDQgPlh6iubC8pna/ddjx8DXWP+Zq7iP/6BV+MHSvlsTOpNRDee/cMfiBAb4oWYPb8p5HMjuFy8Mt5dG+7nvVVSubl45jNkzgTpvuLB7sEjHVufzK4Tc28TnjXVmjw7QWyIU3GSuFFmieDJteWEj0++IKexqf0rzrVXaarWSzMVcbyghgZvmLmg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: release-notify-webhook
      namespace: configarr
