apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    kubernetes.io/name: {{ .Values.name }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  - name: {{ .Values.name }}
    port: 443
    targetPort: 80
    protocol: TCP