apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin
  labels:
    app.kubernetes.io/name: nvidia-device-plugin
data:
  version: v1
  flags:
    migStrategy: "mixed" # Only change from config0.yaml
    failOnInitError: true
    nvidiaDriverRoot: "/"
    plugin:
      passDeviceSpecs: false
      deviceListStrategy: envvar
      deviceIDStrategy: uuid


