---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: instagram-monitor-secrets
  namespace: instagram-monitor
spec:
  encryptedData:
    NOTIFICATION_URL: AgCTQyz5739+UwZTQBPvO++EQgktxzIDGfeLIJA+Q3i+1ZO5nGvMVoBpRSs3F1vFKEk3O1SrKbRKATOMT8KMSApfcSVJ+W1+Mfh7xTwB6UjryEYU2NfMzMUtpWtzAfY4dtnqshF9sEe3wg/+zBWKQGV3U3+4QKVJCm0mW+fmjUo6T+/JmOGfNaG/IAz2lcWcVX/cnPx6Voi5f4IUco9aU3jLkWaRZPMEdpND7boSIfGVWJmsbRT2NjooHHSZiRhkEt50JpYnPAzXt3VmmMUyZTf24U8sJ5OS1VnDZN5XivYa58qiRIaq7xB591zbeotqORkDUCQvzMQ61SETd2mu7TE6tYiutKqMx+cVV+/SYW3BvdjH+GpZfAzExZcY1Kt2R/vT1gTjdGjjiWnZ+812nABFFarRK2ch2XXdHK/jREXnU2Q39Q1Zl3g1TeevsO+ghJGE/cXnjZ1trWbWq4V3zQntYlGnc7W8K7xi4UyEZm9QefwnfoP+ae8TxTb/jc/MVj7zpvJrF5Hv2p2HzYB0oHz/mudGDajhGfSypLxC7PuSvOiITQ7ykmOslLMQWeAoRSw5mZbI9ty35L91YboBBZVFFO1dW66bkUV22zKze9qcgBjsGMY+0c38K/xcNArqEqiNnjTj+dRXcBRHGxTWnJReR31YHuka25rU3qm4p3vTe6X0CKxOZo0jvLXfbKIEfyTL1hGfPFwotoLaxRPpem+DuHcrgIYqdPSPimCYgtOO+Dm1GduJZVvDIMHrRWd2YDU=
  template:
    metadata:
      name: instagram-monitor-secrets
      namespace: instagram-monitor
    type: Opaque
