replicaCount: 1
name: agregarr
targetPort: 7171

image:
  repository: agregarr/agregarr
  # renovate: datasource=docker depName=agregarr/agregarr versioning=loose
  tag: "v2.4.2"
  pullPolicy: IfNotPresent
