replicaCount: 1
name: netdata
targetPort: 19999
puid: 1026
pgid: 100
netdata:
  image:
    repository: netdata/netdata
    pullPolicy: Always
  ingress:
    enabled: false
  parent:
    # envFrom:
    #   - secretRef:
    #       name: netdata
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi
  child:
    envFrom:
      - secretRef:
          name: netdata
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi
  k8sState:
    # envFrom:
    #   - secretRef:
    #       name: netdata
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi