name: kube-prometheus-stack
kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: kube-prometheus-stack.k8s.frost.haus
      hosts:
        - grafana.k8s.frost.haus
      tls:   
      - hosts:
        - grafana.k8s.frost.haus
        secretName: grafana-cert
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: prometheus.k8s.frost.haus
      hosts:
        - prometheus.k8s.frost.haus
      tls:   
      - hosts:
        - prometheus.k8s.frost.haus
        secretName: prometheus-cert
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: "sonarr-exporter"
          static_configs:
            - targets: ["sonarr-exporter:9707"]
        - job_name: "radarr-exporter"
          static_configs:
            - targets: ["radarr-exporter:9708"]
        - job_name: "prowlarr-exporter"
          static_configs:
            - targets: ["prowlarr-exporter:9709"]
        - job_name: "sabnzbd-exporter"
          static_configs:
            - targets: ["sabnzbd-exporter:9710"]
        - job_name: "lidarr-exporter"
          static_configs:
            - targets: ["lidarr-exporter:9711"]
        - job_name: 'pve'
          static_configs:
            - targets:
              - prometheus-pve-exporter.brainboy.local.lan:9221
          metrics_path: /pve
          params:
            module: [default]
            cluster: ['1']
            node: ['1']