name: kube-prometheus-stack
kube-prometheus-stack:
  kubeControllerManager:
    service:
      enabled: true
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: "true"
  kubeProxy:
    service:
      enabled: true
      port: 10249
      targetPort: 10249
  kubeScheduler:
    service:
      enabled: true
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: "true"
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: kube-prometheus-stack.k8s.frost.haus
      hosts:
        - grafana.k8s.frost.haus
      tls:   
      - hosts:
        - grafana.k8s.frost.haus
        secretName: grafana-cert
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: prometheus.k8s.frost.haus
      hosts:
        - prometheus.k8s.frost.haus
      tls:   
      - hosts:
        - prometheus.k8s.frost.haus
        secretName: prometheus-cert
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: "sonarr-exporter"
          static_configs:
            - targets: ["sonarr-exporter.sonarr-exporter.svc.cluster.local:9707"]
        - job_name: "radarr-exporter"
          static_configs:
            - targets: ["radarr-exporter.radarr-exporter.svc.cluster.local:9707"]
        - job_name: "prowlarr-exporter"
          static_configs:
            - targets: ["prowlarr-exporter.prowlarr-exporter.svc.cluster.local:9707"]
        - job_name: "sabnzbd-exporter"
          static_configs:
            - targets: ["sabnzbd-exporter.sabnzbd-exporter.svc.cluster.local:9707"]
        - job_name: 'pve'
          static_configs:
            - targets:
              - pve1.brainboy.local.lan
              # - pve2.brainboy.local.lan
              # - pve3.brainboy.local.lan          
          metrics_path: /pve
          params:
            module: [default]
            cluster: ['1']
            node: ['1']
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: prometheus-pve-exporter.brainboy.local.lan:9221