name: kube-prometheus-stack
kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: kube-prometheus-stack.k8s.frost.haus
      hosts:
        - grafana.k8s.frost.haus
      tls:   
      - hosts:
        - grafana.k8s.frost.haus
        secretName: grafana-cert
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/host: prometheus.k8s.frost.haus
      hosts:
        - prometheus.k8s.frost.haus
      tls:   
      - hosts:
        - prometheus.k8s.frost.haus
        secretName: prometheus-cert