replicaCount: 1
name: organizr
targetPort: 8989
puid: 1026
pgid: 100
ingress:

organizr:
  env:
    TZ: "America/Chicago"
    PUID: 1026
    PGID: 100
  image:
    repository: organizr/organizr
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
  persistence:
    config:
      enabled: false
  service:
    main:
      ports:
        http:
          port: 80