# https://taskfile.dev

version: '3'

vars:
  HELM_NAME: renovate
  HELM_REPO: https://docs.renovatebot.com/helm-charts

tasks:
  deps:
    cmds:
      - helm repo add '{{ .HELM_NAME }}' '{{ .HELM_REPO }}' 1>&2
      - helm dependency build 1>&2
    silent: true
  template:
    cmds:
      - helm template
          --name-template 'infra-homelab-{{ .HELM_NAME }}'
          --namespace '{{ .HELM_NAME }}'
          --values values.yaml
          .
    silent: true
