global:
  imagePullSecrets:
podCidr: "10.244.0.0/16"
podCidrv6: ""

flannel:
  image:
    repository: docker.io/flannel/flannel
    tag: v0.26.2
  image_cni:
    repository: docker.io/flannel/flannel-cni-plugin
    tag: v1.6.0-flannel1
  enableNFTables: false
  args:
  - "--ip-masq"
  - "--kube-subnet-mgr"
  - "-v=10"
  backend: "vxlan"
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

netpol:
  enabled: false
  args:
  - "--hostname-override=$(MY_NODE_NAME)"
  - "--v=2"
  image:
    repository: registry.k8s.io/networking/kube-network-policies
    tag: v0.4.0