apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  source:
    path: external-dns
    repoURL: https://github.com/bdfrost/argocd/charts/external-dns/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true