{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "longhorn-gcp-backups",
    "namespace": "longhorn",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "longhorn-gcp-backups",
        "namespace": "longhorn",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAL1GT52uzdEh+pUkw0NIr94poBpr37LAj55sQdzWYv95RUbG3AVzlU7kH9DlKCsNh1mrqbTtMJg/ig7K6/Dj04bJkc+u/1b2m8Vgwd1rGM8+QVhQ5Ei58Tl0KoBSbgOg8q6RxMPSFl428hTkGlANnWrPnhyo4Hj92NEt96NYljmvnM616IqgLg0z9smDM8JPyNR/IM2goBe2n8SAEBowpcOIqRbY7ZHzxG/JWzWCm18YU1HLUNBt0gBubgNDTLY2202aWT+2n9VUx8hOkR/AKFI9cH5TZx9DXb7FM+zTd+6tXdrgfjj8JL+x6kwAsHCOByIAypIm8WcwWvBNzkPjuUP4YpvGo2Dwna3JGjTsKrFw8VF40+AnlxkwNoq4al8vbpP9Qkt3zLbqt/pcL6cLAlBlXPgFHlG1VMzQU/nKUmZkxta2/RWglErDnHTOGt6ewOGGFn8mtlyTgdGcfNWvdJvDyGr09PIVmriWvJT2jAsjn82DVpyLWtfMg5P8fZIIfPPrgagHEhA6QQPxH2wu5RGEM+9McLPU8qLIbgtXz9w/fXE4+GsA6Cfc+/AOGzUDAjF66JEZem3Czy7jy1TKdkE0SaDcenA5kX1fW7Uf86TlR7qqrGCLe23ANZd5grT7CeMizfQda40tz1+Y31ouXWYbvR9ikyt+iEIP3vGfgT1bQoyncpK4I8TJ+3NIgPGKZq4K7bQiNpKJpHje2RVQz3dxpBB5c1f5QUmROKrZ2a45nVkAX+K9MyAJ3gfemeUjPNhSf4EA0KIq8w5kNchP05m4XwvI5Rn/f2DUGnsYV2DM5Xrxs=",
      "AWS_ENDPOINTS": "AgCOjuKXu0X83zP7ha0QzrY/DVNwVded6BRXRO432Iciv7grrr6hO+QMBXtgda56Q9I385ZShtcCQRxZsp7zNgslrswSTls4lisk4RZb9qWsysx1vbT2I4U3QMgfhjb80QHXys36g2mPDMIazz6qkYvaaUFu31j7oqmyHbRpeeAg8W6mZTDbLk/MpiqI57l/aUn+aIUOF7RZJrZxHSEKkx0M6pbPDeh7AO0jxhckENQ+vGC/32Lm7evhLLYoSFiMoES6sGqAoybmhZ4meGB0eenqdAyOARaITGHq4mGyRWrPrwsxqNqdYJsj8JGe3ELkfY146iM9h+ycfeD0HlwXinkxb7vOA2a1h0YLeK3cOfpw5r6YW4EBd53tMy2/tvrNbEMfjuPUBr8bkcg3cyNfnAdfEIZBWv/muVaG1SoazZa+aJCPtS6Xss8GsyMoUoDs2o5m7BYBEiptOpBxnFu5yAFJu4LGXzvLqTlpOtmRck87aZ8Zu2a0/IvsZX14EKef8zLd4Hs33aEhEFSolnqcB09IChXtIT17lqf9EPyizJxKU2ISvGcw5Lq19SvyKaGNKblDYloCJF+AzcS5VfV3X+qKuvqSe8jcreDniXgxTN3PpjzDhjGwHoCH1v7OuoPz6DaL/wOv+cINgm6WiWDEMdJYAiOVlFnXvhs+VTQGrL3VWG0dJgGOTm+cRvopTPySY2Q6JjZuvBX9eQ+HZmc9Jf7846SZz2loBxYLeoszWXZvcpiReY575xFWIlNy",
      "AWS_SECRET_ACCESS_KEY": "AgBSl+fQbpU1nJsgCzYgoRxH3GwZC5VvhowCIoMbvFK+iFLR3mAna/q9Fcqgdm2+k0KRNs3gwdv6ImMGzKFdaCOQ1Yc3/oJAydkZPQD9U8P7/gIYpm4miWUrqHLA63Y6ma1grKOdi8Aoygbye0lc5xk3jtkWfCS1/zBUWi1li+iM1wvxnyHMwUiW67TshTcxdI1Lpun/13+fGyTqLY5jGa+yI5wFAAzWLdYVbGtii7XYO/32NxGD2IKpUVgze4FAIOrd+fylWmQfXrPDNqr1L2agQtrkqQioOqeYIdC/ezO/kME5eqOwL48yMO66wvalNx1iYH8mDywGUsGAzZzasKGk3J7sAjboL7XrRp7d8VOt+TPd6zZvnldLOKMgvZByTkMFU5P3ue8jiLKcm0biNPtMOoTu0TbIQpkjDpPDzyNLby01EGDX5vvyFSDqIAs0ZxOnOLp3j5MsP95nki48Ju7FwoG32jKvkRxZw+5klA6aKoD9GdlFe1BRQijPJaRaem0iHUhEj/EaglB7xLNHPLh01RiLTdM/Y7prtgPh5kDQMQha6mwmhHyF7WG8UDnVJekhIvkpj8gb7e1cR2Zp2yqksDb8J8jozOza0NQVVTPZkNUT+X52I2HvB1lD/PVCSoUvJ8L/egGWoIgzOQuvbdOWBHwgvMlmbdq4+mecdxRQUKOKHw5bgwHWIWJLNBbC0TJApQ7kMWUqNaPLOORkNOt44CXJlgRuy7JknQC5T8h+I9R7VurCkZVIw+qwqXoJqM5xMhA3xv100g=="
    }
  }
}
