---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  # note this must be a js file to process environment variables
  config.js: |
    module.exports = {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "extends": [
        "config:recommended",
      ],
      "platform": "github",
      "dryRun": false,
      "printConfig": true,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "autodiscover": true,
      "autodiscoverFilter": ["bdfrost/*"],
      "hostRules": [
        {
          hostType: 'docker',
          matchHost: 'docker.io',
          username: process.env.DOCKER_HUB_USERNAME,
          password: process.env.DOCKER_HUB_PASSWORD,
        },
      ],
      "packageRules": [
        {
          // ignore our internal registry
          // https://github.com/renovatebot/renovate/issues/18206
          "matchDatasources": ["docker"],
          "excludePackagePatterns": [""],
          "enabled": true,
          "registryUrls": [
            "https://us-docker.pkg.dev/bdfrost/*",
          ],
        },
      ],
    };

