apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  namespace: kometa
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kometa
              env:
              - name: KOMETA_READ_ONLY_CONFIG
                value: "true"
              - name: KOMETA_RUN
                value: "true"
              - name: KOMETA_WIDTH
                value: "200"
              - name: KOMETA_PLEXTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: plex_token
              - name: KOMETA_TMDBTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tmdb_token
              - name: KOMETA_TAUTULLITOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tautulli_token
              - name: KOMETA_RADARRTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: radarr_token
              - name: KOMETA_SONARRTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: sonarr_token
              - name: KOMETA_TRAKTCLIENTID
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_id
              - name: KOMETA_TRAKTCLIENTSECRET
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_secret
              - name: KOMETA_TRAKTPIN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_pin
              - name: KOMETA_TRAKTACCESS
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_access
              - name: KOMETA_TRAKTREFRESHTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_refresh_token   
              - name: KOMETA_MDBLISTTOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: mdblist_token
              - name: KOMETA_VERBOSE
                value: "1"
              image: kometateam/kometa:2.2.1
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 2Gi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: kometa-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: kometa-config-pvc
            - configMap:
                name: kometa-config
              name: kometa-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
          restartPolicy: OnFailure
