apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  namespace: kometa
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
            runAsUser: 1001
            runAsGroup: 1001
          initContainers:
            - name: render-dynamic-config
              # command: ['sh', '-c', 'chown -R 1001:1001 /config']
              image: chrisjohnson00/jinja-init:v1.0.0
              env:
                - name: JINJA_VAR_PLEX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: plex_token
                - name: JINJA_VAR_TMDB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: tmdb_token
                - name: JINJA_VAR_TAUTULLI_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: tautulli_token
                - name: JINJA_VAR_RADARR_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: radarr_token
                - name: JINJA_VAR_SONARR_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: sonarr_token
                - name: JINJA_VAR_TRAKT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: trakt_client_id
                - name: JINJA_VAR_TRAKT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: trakt_client_secret
                - name: JINJA_VAR_TRAKT_PIN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: trakt_pin
                - name: JINJA_VAR_TRAKT_ACCESS
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: trakt_access
                - name: JINJA_VAR_TRAKT_REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secret
                      key: trakt_refresh_token   
                - name: JINJA_SRC_FILE
                  value: /config_src/config.yaml
                - name: JINJA_DEST_FILE
                  value: /config/config.yaml
                - name: VERBOSE
                  value: "1"
              volumeMounts:
                - name: kometa-config
                  mountPath: /config_src
                - name: config
                  mountPath: /config
          containers:
            - name: kometa
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]                                      
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: kometa-config-pvc
            - configMap:
                name: kometa-config
              name: kometa-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
          restartPolicy: OnFailure
