apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  namespace: kometa
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # securityContext:
          #   runAsUser: 1026
          #   runAsGroup: 100
          containers:
            - name: kometa
              env:
              - name: KOMETA_READ_ONLY_CONFIG
                value: "true"
              - name: KOMETA_RUN
                value: "true"
              - name: KOMETA_WIDTH
                value: "200"
              - name: KOMETA_PLEX_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: plex_token
              - name: KOMETA_TMDB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tmdb_token
              - name: KOMETA_TAUTULLI_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tautulli_token
              - name: KOMETA_RADARR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: radarr_token
              - name: KOMETA_SONARR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: sonarr_token
              - name: KOMETA_TRAKT_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_id
              - name: KOMETA_TRAKT_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_secret
              - name: KOMETA_TRAKT_PIN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_pin
              - name: KOMETA_TRAKT_ACCESS
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_access
              - name: KOMETA_TRAKT_REFRESH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_refresh_token   
              - name: KOMETA_VERBOSE
                value: "1"
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  memory: 125Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: kometa-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: kometa
            - configMap:
                name: kometa-config
              name: kometa-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
          restartPolicy: OnFailure