apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  namespace: kometa
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # securityContext:
          #   runAsUser: 1026
          #   runAsGroup: 100
          containers:
            - name: kometa
              env:
              # - KOMETA_READ_ONLY_CONFIG: true
              # - KOMETA_RUN: true
              # - KOMETA_CONFIG: /config/config.yaml
              # - KOMETA_WIDTH: 200
              - name: PLEX_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: plex_token
              - name: TMDB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tmdb_token
              - name: TAUTULLI_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: tautulli_token
              - name: RADARR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: radarr_token
              - name: SONARR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: sonarr_token
              - name: TRAKT_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_id
              - name: TRAKT_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_client_secret
              - name: TRAKT_PIN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_pin
              - name: TRAKT_ACCESS
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_access
              - name: TRAKT_REFRESH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kometa-secret
                    key: trakt_refresh_token   
              - name: JINJA_SRC_FILE
                value: /config_src/config.yaml
              - name: JINJA_DEST_FILE
                value: /config/config.yml
              - name: VERBOSE
                value: "1"
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  memory: 125Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: kometa-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: kometa
            - configMap:
                name: kometa-config
              name: kometa-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
          restartPolicy: OnFailure