apiVersion: v1
data:
  movies.yaml: |
    templates:
      Holiday:
        smart_label: title.asc
        summary: "A timed collection of <<holiday>> movies and other movies that may relate to the holiday. NOTE: this collection will automatically disappear once the holiday period is over."
        delete_not_scheduled: true
        sort_title: '!AA'
        run_again: true
      #visible_home: true
      #visible_shared: true
        sync_mode: sync
        collection_mode: show_items
      Chart:
        sort_title: +++++_<<collection_name>>
        sync_mode: sync
        smart_label: random
        visible_home: false
        visible_shared: false
        collection_mode: show_items
      Movies:
        radarr_add_missing: true
        optional:
          - collection
          - tmdb_movie
          - trakt_list
          - tmdb_list
        trakt_list_details: <<trakt_list>>
        tmdb_collection_details: <<collection>>
        tmdb_movie: <<tmdb_movie>>
        tmdb_list: <<tmdb_list>>
        sort_title: +++_<<collection_name>>
        collection_order: release
        collection_mode: hide
        sync_mode: sync
      IMDb Genre:
        default:
          title: feature
          limit: 100
        imdb_list:
          - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>
            limit: <<limit>>
          - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>&sort=user_rating,desc
            limit: <<limit>>
        sort_title: +++_<<collection_name>>
        sync_mode: sync
        smart_label: random
        collection_mode: show_items
      Other Genre:
        sort_title: ++_<<collection_name>>
        sync_mode: sync
        smart_label: random
        collection_mode: show_items
      Special Genre:
        sort_title: +_<<collection_name>>
        sync_mode: sync
        smart_label: random
        collection_mode: show_items
      Studio:
        optional:
          - company
        tmdb_company: <<company>>
        sort_title: ++++_<<collection_name>>
        sync_mode: sync
        collection_mode: show_items
      Person:
        smart_filter:
          any:
            actor: tmdb
            director: tmdb
            writer: tmdb
            producer: tmdb
          sort_by: random
          validate: false
        tmdb_person: <<person>>
        sort_title: ~~~~~_<<collection_name>>
        sync_mode: sync
        collection_mode: show_items
    collections:
    #####################################
    #         Studio Collections        #
    #####################################
      Classics:
        plex_search:
          year.gte: 1920
          year.lte: 1959
        sort_title: '###_Classics'
        collection_order: release
      Pixar:
        radarr_tag: Pixar
        imdb_list: https://www.imdb.com/list/ls087911008/
        template: { name: Studio, company: 3 }
        tmdb_company: 3
        summary: A collection of Pixar movies
      DC:
        radarr_tag: DC
        template: {name: Studio}
        imdb_list: https://www.imdb.com/list/ls077827588/
        summary: "The DC Extended Universe (DCEU) is a media franchise and shared universe centered on superheros from DC Comics."
      Marvel:
        radarr_tag: Marvel
        template: {name: Studio}
        imdb_list: https://www.imdb.com/list/ls009410711/
        tmdb_company: 420
        summary: "A collection of movies and shows created by Marvel Studios, comprising of the Marvel Cinematic Universe."
      Studio Ghibli:
        radarr_tag: "Studio Ghibli"
        tmdb_company: 10342
        template: { name: Studio }
        summary: Studio Ghibli Inc. is a Japanese animation film studio headquartered in Koganei, Tokyo. The studio is best known for its animated feature films, and has also produced several short films, television commercials, and one television film. The studio’s mascot and most recognizable symbol is the character, Totoro, a giant cat-like spirit from the 1988 classic, My Neighbor Totoro.
      Disney:
        radarr_tag: Disney
        radarr_add_missing: false
        template: { name: Studio }
          #  imdb_list: 
          #- https://www.imdb.com/search/title/?companies=co0074039&count=250
          #- https://www.imdb.com/list/ls059383351/
          #- https://www.imdb.com/list/ls077114097/
        tmdb_company:
        - 6125
    #####################################
    #     General Movies Collections    #
    #####################################
    #  Alien:
    #    template: {name: Movies, collection: 8091}
    #  The Dark Knight:
    #    template: {name: Movies, collection: 263}
    #    sort_title: +++_Dark Knight
    #  Die Hard:
    #    template: {name: Movies, collection: 1570}
    #  Indiana Jones:
    #    template: {name: Movies, collection: 84}
    #  John Wick:
    #    template: {name: Movies, collection: 404609}
    #  Jurassic Park:
    #    template: {name: Movies, collection: 328}
    #  Middle Earth:
    #    template: {name: Movies, collection: "119,121938"}
    #    summary: A collection of movies and shows set in J.R.R. Tolkien's Middle Earth.
    #  Spider-Man:
    #    template: {name: Movies, collection: "556,125574,531241,573436"}
    #    summary: A collection of all the mainstream Spider-Man movies.
    #  Star Wars:
    #    template: {name: Movies, collection: 10}
    #  The Twilight Saga:
    #    template: {name: Movies, collection: 33514}
    #    sort_title: +++_Twilight Saga
    #####################################
    #        Holiday Collections        #
    #####################################
      Valentine's Day Movies:
        schedule: range(02/01-02/14)
        template: {name: Holiday, holiday: "Valentine's Day"}
        imdb_list:
          - https://www.imdb.com/list/ls000094398/
          - https://www.imdb.com/list/ls057783436/
          - https://www.imdb.com/list/ls064427905/
      St. Patrick's Day Movies:
        schedule: range(03/01-03/17)
        template: {name: Holiday, holiday: "St. Patrick's Day"}
        imdb_list: https://www.imdb.com/list/ls063934595/
      Thanksgiving Movies:
        schedule: range(11/01-11/31)
        sort_title: '!AA'
        template: {name: Holiday, holiday: Thanksgiving}
        imdb_list: 
          - https://www.imdb.com/list/ls000835734/
          - https://www.imdb.com/list/ls091597850/
      Halloween Movies:
        schedule: range(10/01-10/31)
        sort_title: '!AB'
        template: {name: Holiday, holiday: Halloween}
        imdb_list:
          - https://www.imdb.com/list/ls023118929/
          - https://www.imdb.com/list/ls000099714/
          - https://www.imdb.com/list/ls000058693/
          - https://www.imdb.com/search/title/?genres=horror&keywords=haunted-house&sort=moviemeter,asc
        tmdb_collection:
          - 91361    # Halloween Collection
          - 8581     # A Nightmare on Elm Street Collection
          - 1733     # The Mummy Collection
          - 8091     # Alien Collection
        tmdb_movie:
          - 23437    # A Nightmare on Elm Street (2010)
      Christmas Movies:
        schedule: range(12/01-12/31)
        sort_title: '!AB'
        template: {name: Holiday, holiday: Christmas}
        imdb_list: 
          - https://www.imdb.com/list/ls000096828/
          - https://www.imdb.com/list/ls097394442/
          - https://www.imdb.com/list/ls068976997/
          - https://www.imdb.com/list/ls027567380/
    #####################################
    #        Popular Collections        #
    #####################################
      Trending Movies:
        sort_title: +++++++_<<collection_name>>
        template: { name: Chart, num: 1 }
        trakt_chart:
          - chart: trending
            limit: 10
          - chart: popular
            limit: 40
        summary: Movies Trending across the internet
        sync_mode: sync
    #####################################
    #        Hallmark Christmas         #
    #####################################
      Hallmark Christmas:
        mdblist_list:
          - https://mdblist.com/lists/marko8426/hallmark-xmas-movies
          - https://mdblist.com/lists/slimshizn/hallmark-countdown-to-christmas
          - https://mdblist.com/lists/briandnj/hallmark-x-mas
          - https://mdblist.com/lists/kcprophecy/hallmark-christmas-ywa8un60mz
          - https://mdblist.com/lists/setifer/hallmarkchristmasfrom2015
          - https://mdblist.com/lists/vectrexgamer/hallmark-original-christmas-movies
          - https://mdblist.com/lists/vectrexgamer/hallmark-hall-of-fame-christmas-movies
          - https://mdblist.com/lists/mdatum/hallmark
        trakt_list:
          - https://trakt.tv/users/ad76/lists/hallmark-christmas
          - https://trakt.tv/users/milly84/lists/hallmark-2025
          - https://trakt.tv/users/midnitewolf/lists/hallmark-premieres-2024-2025
          - https://trakt.tv/users/prada3721/lists/hallmark-premieres-2024-2025
          - https://trakt.tv/users/midnitewolf/lists/hallmark-romance-premieres-2024-2025
          - https://trakt.tv/users/tex24601/lists/hallmark-christmas-movies
          - https://trakt.tv/users/veninjak/lists/hallmark-christmas-movies
          - https://trakt.tv/users/kylep09/lists/hallmark-holiday
          - https://trakt.tv/users/yoly76/lists/holiday-tv-movies-present
          - https://trakt.tv/users/mzdiobolik/lists/hallmark-christmas-movies
        sort_title: '###Hallmark Christmas'
        collection_order: release.desc
        radarr_tag: Hallmark Christmas
        sync_mode: sync      
        radarr_add_missing: true
    #####################################
    #        Hallmark Fall              #
    #####################################
      Hallmark Fall:
        trakt_list:
          - https://trakt.tv/users/linsk/lists/hallmark-fall
          - https://trakt.tv/users/laci88/lists/hallmark-fall-movies
          - https://trakt.tv/users/sflix/lists/hallmark-fall-movies
          - https://trakt.tv/users/stillaggin/lists/hallmark-fall-2023
        sort_title: '###Hallmark Fall'
        collection_order: release.desc
        radarr_tag: Hallmark Fall
        sync_mode: sync
        radarr_add_missing: true
    #####################################
    #        Hallmark                   #
    #####################################
      Hallmark:
        mdblist_list:
          - https://mdblist.com/lists/SynAcksHM/hallmark
        trakt_list:
        - https://trakt.tv/users/alexamaclaud/lists/hallmark-2
        - https://trakt.tv/users/ad76/lists/hallmark-movies-mysteries
        - https://trakt.tv/users/ad76/lists/hallmark-movies
        - https://trakt.tv/users/hollywood-heidi/lists/hallmark-hallmark-mysteries-hallmark-romances-1
        - https://trakt.tv/users/hollywood-heidi/lists/hallmark-hallmark-mysteries-hallmark-romances-2
        - https://trakt.tv/users/midnitewolf/lists/hallmark-premieres-2024-841fc509-8aca-4c90-995b-ddb198d9e259
        - https://trakt.tv/users/serralee/lists/hallmark-movies-2024
        - https://trakt.tv/users/midnitewolf/lists/hallmark-premieres-2024-2025
        - https://trakt.tv/users/crossoverenserie/lists/hallmark-2025-movies-shows
        - https://trakt.tv/users/goonerdom/lists/hallmark-2024
        - https://trakt.tv/users/midnitewolf/lists/hallmark-romance-premieres-2024-2025
        sort_title: '###Hallmark'
        collection_order: release.desc
        radarr_tag: Hallmark
        sync_mode: sync
        radarr_add_missing: true
        template: {name: Movies}
        imdb_search:
          type: movie
          company: co0939898
          limit: 999
    #####################################
    #        GAC                        #
    #####################################
      GAC:
        trakt_list:
          - https://trakt.tv/users/loopher/lists/great-american-family-channel-christmas-list
          - https://trakt.tv/users/kwolfe/lists/great-american-family-movies
        sort_title: '###GAC'
        collection_order: release.desc
        radarr_tag: GAC
        sync_mode: sync
        radarr_add_missing: true
        imdb_search:
          type: movie
          company: co0814123
          limit: 999
    #####################################
    #       Christmas                   #
    #####################################
      Christmas:
        radarr_add_missing: true
        template: {name: Holiday, poster: https://theposterdb.com/api/assets/111696}
        trakt_list:
          - https://trakt.tv/users/crossoverdeseries/lists/other-christmas-2022
          - https://trakt.tv/users/movistapp/lists/christmas-movies
          - https://trakt.tv/users/pualani78/lists/christmas-2020
          - https://trakt.tv/users/veninjak/lists/complete-christmas-2021-copy
          - https://trakt.tv/users/veninjak/lists/christmas-2022-copy
        imdb_list:
          - https://www.imdb.com/list/ls025976544/
          - https://www.imdb.com/list/ls003863000/
          - https://www.imdb.com/list/ls027454200/
          - https://www.imdb.com/list/ls027886673/
          - https://www.imdb.com/list/ls097998599/
        summary: Christmas film is a genre that revolves around the plot involving Christmas.
kind: ConfigMap
metadata:
  name: movie-config
  namespace: kometa