apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kometa
  name: kometa-config-pvc
  namespace: kometa
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi