apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kometa
  name: kometa
  namespace: kometa
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi