apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: agregarr/agregarr
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.targetPort }}
        env:
        - name: HAS_IPV6
          value: "false"
        volumeMounts:
        - name: {{ .Values.name }}-config
          mountPath: /app/config
      volumes:
        - name: {{ .Values.name }}-config
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  resources:
    requests:
      storage: 2Gi