name: cloudflared
puid: 1026
pgid: 100
cloudflare-tunnel:
  cloudflare:
    tunnelName: "k8s"
    secretName: cloudflared-cloudflare-tunnel
    enableWarp: false
    ingress:
      - hostname: argocd.frost.haus
        service: https://argocd.frost.haus:443
      # - hostname: 1.frost.haus
      #   service: https://guestbook.frost.haus
      - service: http_status:404
        hostname: "*.frost.haus"
      # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 200.
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: "2025.5.0"
  replicaCount: 2
  metrics: 0.0.0.0:2000
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    sysctls:
    - name: net.ipv4.ping_group_range
      value: "0           200000000"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi