---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: speedtest-tracker-secrets
  namespace: speedtest-tracker
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBfrryIzYVpxcWZVtBtLmRob6aD+i8I8obAsCkeDGFXHsVfnviGK51L5oBnJaSWKg+Slwzy3D3TGkppWYFbru4ZCkLZw1o77nr3FpqJHJA+uNF4cSBB68u6kjyNnkzkz3xkeGofMuusybGh+OH3ky+ilpYUEi29GOcFXuQbAHU1PDBcnhyCfeq5dXOIcmji+1vSbJ2E9o94Vz8KY/xIjvyGjyL6Qj7YRQ1Ru4GNt913EFFK6+azF3q95wLAeCZWjL8XZez7YgRyk8BVtuxKnTri3NLtjujS8zIRYMU3boBQ+pYa4KBBJ3YAMttMSzJLwYtdeX1sIS4VWotfow9rKg4Fkn8VKAokvE82DOfCNiMzXEen64fL3TaC1NlKZVBWqtkJvFjDJA4ayDsroK9A+xEZmlSf2leN/Z2ZZaqjvbiWRreksyDLOl99AoxtESO1ey78qWrQxHjqi2NYlMYn6y+7nqwfcXp1Gac79kAHP9lvhhiyuLW5FZmo6/ZKcVgykxsZi7fYYsEF4Qqyy1w3MbXot0SB6aaXLT2cIVGT/QSo5SDYe2NYaex9zBYSd0sTT4DSHa++gzpwi1rHj+3MT/daNcHuEfisx0qQTShVJNWLDe/BSn6Gcypu7F7BaIArNXw4DcD+YOPvdzaYIKrIWdJ3WBmstQmknn1wK0kI0XLcLbPAGpuHc/65w164wYap6CDLgsSyuOAhNdAa0JmAkeX5Lr+2dhuR+T4=
    APP_KEY: AgB1aXRBcmzXWmvGhL7v54+dNXUo/vDsWNtKwxroivO/WG1cCV14sFnwBX00lCmyBx7MwkYxY8EHxK6J/usb7gyvNbSBfKoNfl4vg3K3oiNIZ/Oe4oELT/rZl9pgrHqyF7TYSkMeNw554OSdqUDHEOM/I2NMmcG0SbZ2e3tkaDvwzbccPG9KxNyhI7Qhc+sSOVJ6ginMutkdi069FRlr22otm7vqx4O1cOGye9T9fYXnx1b1GBKehhtUDAyIyAiykdDzjQaO9m5VA3Vb0mtzlrpkFdm8OSZs353wPfcxGtYvOEKAT7bqrRLC+UjfApev1QYy42x43O0zk4GUOAmAw6SajXku52Kg3LmhDjTBY9l8rBQxl6eA+kpfXRN7H21QSzPjHFbNaAzbS5E0bd62f2S0XR1VSYq7PJJjSX4aRzvoKO+DuKtNPgAtkUTtIJgKynbG/QH/Taii1tqJCRRa/6t6qb3ge3vuDTkQiFI0MTtY4hiZ2uArl+noR/R1te5q5C08TolQvnj4NHvQy/G7Zg9pqwwR5rMZ6a4+7S4fooO7GjGr5I3fTp2gZ14DMIMXRNQoFlKdF57MIeDljlojKZyDmNdVVOBGY7u04lTs5Xd08RH38dXW8Ko2gCmMpL+LOFxSl/BdpwnJ3UOMHdv4AfUSgJlavXAZFqM+fum3LPWkgqVo9aFppR7j6S7oTmsb3h6p+PlDbSHqFSc7DR9MSeML6u+0YwfBtm5Uokpa/O1x8BSpW7vX/AgokhZKeopDv3wu63c=
  template:
    metadata:
      creationTimestamp: null
      name: speedtest-tracker-secrets
      namespace: speedtest-tracker
