apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig
  namespace: monitoring
  labels:
    alertmanagerConfig: global
spec:
    route:
        receiver: 'slack-notifications'
    receivers:
    - name: 'slack'
        slackConfigs:
        - channel: '#general'
        slack_api_url_file: /etc/alertmanager/secrets/alertmanager-secrets/slack_api_url
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"