apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # server.insecure: "true"
  # Redis server hostname and port (e.g. argocd-redis:6379)
  redis.server: "argocd-redis:6379"
  # Enable compression for data sent to Redis with the required compression algorithm. (default 'gzip')
  redis.compression: gzip
  # Redis database
  redis.db:

  # ## Server properties
  # # Listen on given address for incoming connections (default "0.0.0.0")
  # server.listen.address: "0.0.0.0"
  # # Listen on given address for metrics (default "0.0.0.0")
  # server.metrics.listen.address: "0.0.0.0"
  # # Set the logging format. One of: text|json (default "text")
  # server.log.format: "text"
  # # Set the logging level. One of: debug|info|warn|error (default "info")
  # server.log.level: "info"