apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: "2025-01-04T22:45:00Z"
  generation: 1
  name: default
  namespace: argocd
  resourceVersion: "6547"
  uid: 3ffaffa0-1d80-4e04-9f3b-a2f11663afdf
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  orphanedResources:
    warn: false
    