apiVersion: v1
kind: ConfigMap
data:
  kustomize.buildOptions: --enable-helm
  accounts.bfrost: apiKey, login
  accounts.bfrost.enabled: "true"
  application.resourceTrackingMethod: annotation
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  url: https://argocd.frost.haus
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template /templates --name-template $ARGOCD_APP_NAME --include-crds > /templates/*.yml && kustomize build"]        
   # dex.config: |
  #   connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: fb563b3a8dd7ea52f683
  #       clientSecret: $argocd-auth:dex.github.clientSecret
  #       orgs:
  #       - name: argoproj
  #         teams:
  #         - argo-rollouts-approvers
  #         - argo-workflows-approvers
  #         - argocd-approvers
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
