apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: letsencrypt
    kind: Issuer
  commonName: argocd.frost.haus
  dnsNames:
  - argocd.frost.haus
