apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- argocd-cm.yaml
- argocd-server-service.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml
- argocd-cmd-params-cm.yaml
- argocd-server-ingress.yaml
# - argocd-rbac-cm.yaml
# - rollouts-extension.yaml
# More examples
# - github.com/argoproj/argo-cd/manifests/