apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bfrost@brainboy.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          ingress:
            class: nginx
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token