---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    sabnzbd_apikey: AgCiu8jYb5SAbHtZusvxuBp/0o+SzXuVBNGdaS/SQ4QoZiXJ3gjlO8eNj6ZHdtRtv+vtPDFY9Ik7iGQB5XqP4/N+9X0lmSxF0ub0jlzyBJMDessf+jTn6GQpCVNoSvmDTZwM2ecdNXLfv6hrPiKrv0J3SqDDCet2ttMQhNg0fcD8tdibxGCKXiAXdI1Igtz6Sj1JCiOtCD7OF/2TInt5eh2CVRG7IqnW7qinF53vWdET7CZl+Pm57yNG9GtFkuo9ZeH55hXzpA5hqOOBkaf3WRQsaMQhBQThQ5vloQn5seYCSeIfaZcO21E3qQNI05wqR8mA8MY+SOgcMXhWrcRpd0r1I5TCJp+kJTH3RiNnE4e+jahz1GCQ16nXf5ZM6/OXCyYf89g5tRL+9QvrUFAAz04QCPeZ7GGxOHeMdy8KR4hLwcb8ORHD5y/kq96BLL6Ut+8rFf6IcWH+1VhQKMREJI+1SZPEc9PMFkJ+rXq5UaKHUfJGsRy151kNUzfPMeLJcp8pkiCquW/62uQjiVTuAf93PUQkn36MC0mrcH69V0c+dgcUkX+7YgJYM/YcaeKucl0aU0YSxB/6O5aPUIwltaQBZ6AlcDcT3epGQPuadY0KNBQ5kAqpY9fh6jaq+6cFSEZX3rLgFFUZoPmAXTj/rzKV+Uby/PK6DlnoSDrMVPZIbsloLyN4NQF0cOwNZ81G4FDtWp+qOq7Ln+s5AOSklffc+V2ylidtO6oeqXIsF3uAiw==
    x-plex-token: AgCDmW61AeNhtcRwBpxLj5HX/Jd9ulVQ6KLLpk7xChhu0kvYbvBWIvip3fD5q6u23xTtNP6j8yDKZQ9SnTzPnIr+58xcVc7qgrHGWy+WAvluZv7oQNVLfiaiz6/kI66fwxHG6HqmDqWTyOIKdQ0n2b/zK//ABunBTIrlC/RV51PtM5xWDfCIigTEtoZUmga13S7g0QGNRSgqKzD/VQY5euVH3a4ajCiwo9NWm/MrFyaHbrWKh5Q2CIMo/B+fW1yuFj+J8IAY//RVl7pOsgvprVowvTyuyY49tNwMuV8bToQ0PXGV1t13ISWQPhgKayi/eLI9L7DDmtCF7HxfGgvujhxcSAx1vN4HeKvvxcjaym7pXAsS8JrEVTwAVWWEWBPw4HnLOBw39vCC0eaT/b0ajhaQqod2+4BftlpXFuLgYNCr3BR3VjwHUnBy7Cn3w4rNy9t0uEM2PcXSwvR6+XU8Crpombdqf1o7u1ZL/68JcTEwFnUyUANXYmLtcbDb7ELYIsDhx6d2ps94/uUS3kqFRMG9pOUqNL4LZV6xJ+IeUejaIRtEvDhKP6hsl+tB9/jBEhhsPEbars9qsXWiIaqf183DvkakYgqrqDDpAeDzJ4L6auhUO2q79IE3LxtTZvDXPZ+m7ExoLF1OLIQBvqa88G3d20ooykS0MJ7ORnUGHCl8AFOO4wugx6MJnRAH2O9THwut2oDSFHhXDT1C61zUwdecGtelXA==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secrets
      namespace: homepage
