kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflared-cloudflare-tunnel
  namespace: cloudflared
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflared-cloudflare-tunnel
      namespace: cloudflared
      creationTimestamp: null
  encryptedData:
    credentials.json: AgAWggM1ydjrQoF9JKkVZ9VtBpTc4VMiRmnip1drrOcpF4JyPFJFOXe8a87bhyd/nmW5dE9Iv1pFsksj8RzWB8YMV8dV7S+RbAvwSMX6ogBXdkTDBfj/3rsFSMtKGicRwYDvgpBQF6XKuPdqFGxvCVJmdwwnA8lnOY9B0korYVwFakmcOYvRx5LRNS7CPCHUgg28sVVBQbut92NrlGuv7WPvrJNJRw8GPq/zuUERgOjq829PW0AriEib26wPYSjxO9mGRqJ0eaBerVlA2tu+0BSouBuzjBDF8+/53KiNX6dsQNQDQWguVWaSvJyKErl/dRiPSar3JthPBTmDDAd53/VlZ88bN7+e+338E4EIu5plR+93YjNcYFeUXk4UAG7/z2R+a5OeYVFQs7ZV41uVqXCDDnll52qW/K7QBndo6SiuGDc6UgwaXwHdwxTqV2Yx4UxrF5Otc9AzIh8sBpOFAl+CplF4JG5oKQRGiBtrLkftr5oEmaTLK3IqIMynIpejmPe6K/bCkT3hAmkJL7Sdf8Myeg6+XRqfMeRNsuGdPJRDhFmrtx8OjfBvx+o2vyqcOSsjXsjxSygMpcogKA2ugWLmKDnoRBFHslKH5V15stuUNA1yim1aN47RHuYHCPh3sLC9tiCoFZynRotwRqFBzAznTBTDa/b4hat8nGfQa/zwm/dr4SPqFLGwd727tSmV+1H81BKpBccDp4+Mg8BtgKOQD0GCBi/34YfCGheR2auHV6eMJkWCFhJYoqPlt4+V1iqH7gGuzrD5jqtBsZpP3SqL63uB6wtXbiDA01wTwlte3eqMhB9R5QWGHvxRIfwZ/s0KT2xJ8M8mTEY62wipNXgyelYZwSH1+GWjts9CIXyOYDjjIQsyL6ud5VY8Qm1iFr22bqh/+GCHpOHQttSNGy1kIiPcPFyxfNoU6KMczJPJqWcbCxszw8gbltYxKXayTvgs