apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: dozzle-scheduled-snapshot
  namespace: dozzle
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: dozzle-config-pvc-synology
  snapshotFrequency: 1d
  snapshotRetention: 7d