apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: kometa-scheduled-snapshot
  namespace: kometa
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: kometa-config-pvc
  snapshotFrequency: 1d
  snapshotRetention: 7d