apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: seerr-scheduled-snapshot
  namespace: seerr
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: seerr-pvc
  snapshotFrequency: 1d
  snapshotRetention: 7d