apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: pihole-scheduled-snapshot
  namespace: pihole
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: pihole-config-pvc
  snapshotFrequency: 1d
  snapshotRetention: 7d