apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: plex-scheduled-snapshot
  namespace: plex
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: plex-config-pvc
  snapshotFrequency: 1d
  snapshotRetention: 7d