apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: radarr-scheduled-snapshot
  namespace: radarr
spec:
  snapshotClassName: synology-csi-iscsi-delete
  persistentVolumeClaimName: radarr-config-pvc
  snapshotFrequency: 1d
  snapshotRetention: 7d