# https://github.com/plexguide/Radarr-Hunter
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sonarr-huntarr
  name: sonarr-huntarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr-huntarr
  template:
    metadata:
      labels:
        io.kompose.service: sonarr-huntarr
    spec:
      containers:
        - env:
            - name: API_KEY
              value: your-api-key
            - name: API_URL
              value: http://your-sonarr-address:8989
            - name: DEBUG_MODE
              value: "false"
            - name: MAX_MISSING
              value: "1"
            - name: MAX_UPGRADES
              value: "5"
            - name: MONITORED_ONLY
              value: "true"
            - name: RANDOM_SELECTION
              value: "true"
            - name: SEARCH_TYPE
              value: both
            - name: SLEEP_DURATION
              value: "900"
            - name: STATE_RESET_INTERVAL_HOURS
              value: "168"
          image: huntarr/4sonarr:latest
          name: huntarr
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: radarr-hunter
  name: radarr-hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: radarr-hunter
  template:
    metadata:
      labels:
        io.kompose.service: radarr-hunter
    spec:
      containers:
        - env:
            - name: API_KEY
              value: your-api-key
            - name: API_URL
              value: http://radarr:7878
            - name: MAX_MOVIES
              value: "1"
            - name: RANDOM_SELECTION
              value: "true"
            - name: REFRESH_DURATION
              value: "30"
            - name: SLEEP_DURATION
              value: "600"
          image: admin9705/radarr-hunter
          name: radarr-hunter
      restartPolicy: Always